import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

/// ═══════════════════════════════════════════════════════════════════════════
/// DEVICE SERVICE
/// Connects hardware telemetry to Firestore and streams AI Insights.
/// ═══════════════════════════════════════════════════════════════════════════
class DeviceService {
  final _firestore = FirebaseFirestore.instance;

  /// Streams the 20 most recent hardware telemetry records
  Stream<List<Map<String, dynamic>>> telemetryStream(String fighterId) {
    return _firestore
        .collection('telemetry')
        .where('fighterId', isEqualTo: fighterId)
        .orderBy('timestamp', descending: true)
        .limit(20)
        .snapshots()
        .map((snap) => snap.docs.map((d) => d.data()).toList());
  }

  /// Streams the live AI readiness and fatigue scores generated by the Cloud Functions
  Stream<Map<String, dynamic>?> aiInsightsStream(String fighterId) {
    return _firestore
        .collection('ai_insights')
        .doc(fighterId)
        .snapshots()
        .map((doc) => doc.data());
  }

  /// Used by the BLE / HealthKit integration to record raw hardware data
  Future<void> logTelemetry(Map<String, dynamic> payload) async {
    try {
      payload['timestamp'] ??= FieldValue.serverTimestamp();
      await _firestore.collection('telemetry').add(payload);
    } catch (e) {
      debugPrint('Failed to log telemetry: $e');
    }
  }
}
