/// GlobalRankingService — hype score + momentum score engine for fighter/gym/event global ranking.
class GlobalRankingService {
  static final GlobalRankingService _instance =
      GlobalRankingService._internal();
  factory GlobalRankingService() => _instance;
  GlobalRankingService._internal();

  /// Compute a hype score (0–100) from engagement + reach + recency.
  /// [engagement]  total likes + comments + shares
  /// [reach]       estimated audience size
  /// [daysSinceActive] days since last active content
  double computeHypeScore({
    required int engagement,
    required int reach,
    required int daysSinceActive,
  }) {
    if (reach <= 0) return 0;
    final engagementRate = (engagement / reach).clamp(0.0, 1.0);
    final recencyBoost = (1 / (1 + daysSinceActive * 0.1)).clamp(0.0, 1.0);
    final raw = (engagementRate * 60) + (recencyBoost * 40);
    return raw.clamp(0.0, 100.0);
  }

  /// Compute a momentum score (0–100) from trajectory over recent periods.
  /// [previousEngagement] engagement in the prior period
  /// [currentEngagement]  engagement in the current period
  double computeMomentumScore({
    required int previousEngagement,
    required int currentEngagement,
  }) {
    if (previousEngagement <= 0) return 50.0;
    final delta = currentEngagement - previousEngagement;
    final ratio = delta / previousEngagement;
    // Map ratio from [-1, +1] → [0, 100]
    return ((ratio + 1) * 50).clamp(0.0, 100.0);
  }

  /// Compute a composite global rank score.
  double globalScore({
    required double hypeScore,
    required double momentumScore,
    required int wins,
    required int losses,
    bool isChampion = false,
  }) {
    final record = wins + losses > 0 ? wins / (wins + losses) : 0.5;
    final championBonus = isChampion ? 15.0 : 0.0;
    final raw =
        (hypeScore * 0.4) +
        (momentumScore * 0.3) +
        (record * 100 * 0.3) +
        championBonus;
    return raw.clamp(0.0, 100.0);
  }

  /// Returns a rank label from a global score.
  String rankLabel(double score) {
    if (score >= 90) return 'ELITE';
    if (score >= 75) return 'TOP 10';
    if (score >= 60) return 'RANKED';
    if (score >= 40) return 'RISING';
    return 'PROSPECT';
  }

  /// Sample leaderboard entries for demo display.
  List<GlobalRankEntry> getDemoLeaderboard() {
    return [
      // ── ELITE tier ──────────────────────────────────────────────
      const GlobalRankEntry(
        id: '1',
        name: 'George Kambosos Jr',
        weightClass: 'Lightweight',
        sport: 'Boxing',
        hypeScore: 94.2,
        momentumScore: 88.5,
        globalScore: 91.8,
        wins: 22,
        losses: 2,
        isChampion: false,
        region: 'AU',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '2',
        name: 'Valentina Shevchenko',
        weightClass: 'Flyweight',
        sport: 'MMA',
        hypeScore: 96.1,
        momentumScore: 91.0,
        globalScore: 94.5,
        wins: 23,
        losses: 4,
        isChampion: true,
        region: 'KG',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '3',
        name: 'Amanda Nunes',
        weightClass: 'Bantamweight',
        sport: 'MMA',
        hypeScore: 97.5,
        momentumScore: 85.0,
        globalScore: 93.2,
        wins: 21,
        losses: 5,
        isChampion: true,
        region: 'BR',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '4',
        name: 'Reza Khan',
        weightClass: 'Welterweight',
        sport: 'MMA',
        hypeScore: 87.1,
        momentumScore: 92.0,
        globalScore: 88.4,
        wins: 14,
        losses: 3,
        isChampion: false,
        region: 'AE',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '5',
        name: 'Katie Taylor',
        weightClass: 'Lightweight',
        sport: 'Boxing',
        hypeScore: 95.8,
        momentumScore: 89.3,
        globalScore: 93.0,
        wins: 23,
        losses: 1,
        isChampion: true,
        region: 'IE',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '6',
        name: 'Claressa Shields',
        weightClass: 'Middleweight',
        sport: 'Boxing',
        hypeScore: 93.4,
        momentumScore: 90.1,
        globalScore: 92.1,
        wins: 14,
        losses: 0,
        isChampion: true,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '7',
        name: 'Tim Tszyu',
        weightClass: 'Super Welterweight',
        sport: 'Boxing',
        hypeScore: 86.1,
        momentumScore: 83.4,
        globalScore: 84.9,
        wins: 25,
        losses: 1,
        isChampion: false,
        region: 'AU',
        gender: 'M',
      ),

      // ── TOP 10 tier ─────────────────────────────────────────────
      const GlobalRankEntry(
        id: '8',
        name: 'Stamp Fairtex',
        weightClass: 'Bantamweight',
        sport: 'Muay Thai',
        hypeScore: 91.2,
        momentumScore: 87.4,
        globalScore: 89.8,
        wins: 68,
        losses: 19,
        isChampion: true,
        region: 'TH',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '9',
        name: 'Zhang Weili',
        weightClass: 'Strawweight',
        sport: 'MMA',
        hypeScore: 90.5,
        momentumScore: 88.2,
        globalScore: 89.1,
        wins: 24,
        losses: 3,
        isChampion: true,
        region: 'CN',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '10',
        name: 'Anissa Meksen',
        weightClass: 'Featherweight',
        sport: 'Kickboxing',
        hypeScore: 88.9,
        momentumScore: 84.6,
        globalScore: 87.2,
        wins: 107,
        losses: 6,
        isChampion: true,
        region: 'FR',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '11',
        name: 'Saenchai',
        weightClass: 'Featherweight',
        sport: 'Muay Thai',
        hypeScore: 89.7,
        momentumScore: 78.5,
        globalScore: 85.4,
        wins: 299,
        losses: 46,
        isChampion: false,
        region: 'TH',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '12',
        name: 'Alexa Grasso',
        weightClass: 'Flyweight',
        sport: 'MMA',
        hypeScore: 87.3,
        momentumScore: 86.7,
        globalScore: 85.9,
        wins: 16,
        losses: 3,
        isChampion: true,
        region: 'MX',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '13',
        name: 'Savannah Marshall',
        weightClass: 'Middleweight',
        sport: 'Boxing',
        hypeScore: 84.1,
        momentumScore: 88.9,
        globalScore: 85.3,
        wins: 13,
        losses: 1,
        isChampion: false,
        region: 'GB',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '14',
        name: 'Alex Pereira',
        weightClass: 'Light Heavyweight',
        sport: 'MMA',
        hypeScore: 92.0,
        momentumScore: 90.5,
        globalScore: 88.6,
        wins: 11,
        losses: 2,
        isChampion: true,
        region: 'BR',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '15',
        name: 'Priya Nair',
        weightClass: 'Strawweight',
        sport: 'MMA',
        hypeScore: 80.0,
        momentumScore: 85.3,
        globalScore: 80.2,
        wins: 9,
        losses: 1,
        isChampion: false,
        region: 'IN',
        gender: 'F',
      ),

      // ── RANKED tier ─────────────────────────────────────────────
      const GlobalRankEntry(
        id: '16',
        name: 'Emeka Obi',
        weightClass: 'Middleweight',
        sport: 'Bare Knuckle',
        hypeScore: 76.4,
        momentumScore: 81.1,
        globalScore: 77.3,
        wins: 11,
        losses: 5,
        isChampion: false,
        region: 'NG',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '17',
        name: 'Bec Rawlings',
        weightClass: 'Flyweight',
        sport: 'Bare Knuckle',
        hypeScore: 78.2,
        momentumScore: 76.0,
        globalScore: 76.8,
        wins: 5,
        losses: 2,
        isChampion: true,
        region: 'AU',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '18',
        name: 'Christine Ferea',
        weightClass: 'Featherweight',
        sport: 'Bare Knuckle',
        hypeScore: 74.5,
        momentumScore: 79.2,
        globalScore: 75.9,
        wins: 6,
        losses: 1,
        isChampion: true,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '19',
        name: 'Tiffany Van Soest',
        weightClass: 'Bantamweight',
        sport: 'Kickboxing',
        hypeScore: 79.3,
        momentumScore: 74.8,
        globalScore: 76.1,
        wins: 26,
        losses: 5,
        isChampion: false,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '20',
        name: 'Denise Kielholtz',
        weightClass: 'Flyweight',
        sport: 'Kickboxing',
        hypeScore: 76.8,
        momentumScore: 78.5,
        globalScore: 76.3,
        wins: 55,
        losses: 3,
        isChampion: false,
        region: 'NL',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '21',
        name: 'Loma Lookboonmee',
        weightClass: 'Strawweight',
        sport: 'Muay Thai',
        hypeScore: 74.2,
        momentumScore: 80.1,
        globalScore: 75.5,
        wins: 10,
        losses: 4,
        isChampion: false,
        region: 'TH',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '22',
        name: 'Mike Perry',
        weightClass: 'Welterweight',
        sport: 'Bare Knuckle',
        hypeScore: 82.1,
        momentumScore: 77.3,
        globalScore: 78.5,
        wins: 5,
        losses: 0,
        isChampion: true,
        region: 'US',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '23',
        name: 'Israel Adesanya',
        weightClass: 'Middleweight',
        sport: 'MMA',
        hypeScore: 88.3,
        momentumScore: 72.0,
        globalScore: 79.4,
        wins: 24,
        losses: 3,
        isChampion: false,
        region: 'NZ',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '24',
        name: 'Superbon Singha Mawynn',
        weightClass: 'Featherweight',
        sport: 'Kickboxing',
        hypeScore: 81.4,
        momentumScore: 78.9,
        globalScore: 79.0,
        wins: 113,
        losses: 34,
        isChampion: true,
        region: 'TH',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '25',
        name: 'Denice Zamboanga',
        weightClass: 'Bantamweight',
        sport: 'MMA',
        hypeScore: 72.8,
        momentumScore: 78.4,
        globalScore: 73.6,
        wins: 10,
        losses: 3,
        isChampion: false,
        region: 'PH',
        gender: 'F',
      ),

      // ── RISING tier ─────────────────────────────────────────────
      const GlobalRankEntry(
        id: '26',
        name: 'Jade Masson-Wong',
        weightClass: 'Strawweight',
        sport: 'Brawling',
        hypeScore: 68.5,
        momentumScore: 82.4,
        globalScore: 71.2,
        wins: 7,
        losses: 2,
        isChampion: false,
        region: 'GB',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '27',
        name: 'Tai Emery',
        weightClass: 'Featherweight',
        sport: 'Bare Knuckle',
        hypeScore: 80.7,
        momentumScore: 74.3,
        globalScore: 72.1,
        wins: 4,
        losses: 1,
        isChampion: false,
        region: 'AU',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '28',
        name: 'Jasmine Parr',
        weightClass: 'Lightweight',
        sport: 'Boxing',
        hypeScore: 71.2,
        momentumScore: 76.8,
        globalScore: 70.5,
        wins: 8,
        losses: 1,
        isChampion: false,
        region: 'AU',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '29',
        name: 'Shara Magomedov',
        weightClass: 'Middleweight',
        sport: 'MMA',
        hypeScore: 75.3,
        momentumScore: 81.9,
        globalScore: 72.8,
        wins: 15,
        losses: 0,
        isChampion: false,
        region: 'RU',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '30',
        name: 'Jackie Buntan',
        weightClass: 'Strawweight',
        sport: 'Muay Thai',
        hypeScore: 70.1,
        momentumScore: 75.6,
        globalScore: 69.8,
        wins: 20,
        losses: 5,
        isChampion: false,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '31',
        name: 'Ruqsana Begum',
        weightClass: 'Bantamweight',
        sport: 'Muay Thai',
        hypeScore: 66.3,
        momentumScore: 73.2,
        globalScore: 67.4,
        wins: 8,
        losses: 3,
        isChampion: false,
        region: 'GB',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '32',
        name: 'Jai Opetaia',
        weightClass: 'Cruiserweight',
        sport: 'Boxing',
        hypeScore: 89.8,
        momentumScore: 88.1,
        globalScore: 88.4,
        wins: 26,
        losses: 0,
        isChampion: true,
        region: 'AU',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '33',
        name: 'Mikaela Mayer',
        weightClass: 'Featherweight',
        sport: 'Boxing',
        hypeScore: 77.5,
        momentumScore: 73.9,
        globalScore: 74.2,
        wins: 18,
        losses: 1,
        isChampion: false,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '34',
        name: 'Casey O\'Neill',
        weightClass: 'Flyweight',
        sport: 'MMA',
        hypeScore: 72.4,
        momentumScore: 78.0,
        globalScore: 73.3,
        wins: 10,
        losses: 2,
        isChampion: false,
        region: 'AU',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '35',
        name: 'Jonas Sultan',
        weightClass: 'Bantamweight',
        sport: 'Boxing',
        hypeScore: 69.2,
        momentumScore: 71.4,
        globalScore: 67.8,
        wins: 18,
        losses: 6,
        isChampion: false,
        region: 'PH',
        gender: 'M',
      ),

      // ── PROSPECT tier ───────────────────────────────────────────
      const GlobalRankEntry(
        id: '36',
        name: 'Natasha Jonas',
        weightClass: 'Welterweight',
        sport: 'Boxing',
        hypeScore: 62.1,
        momentumScore: 68.4,
        globalScore: 63.5,
        wins: 14,
        losses: 2,
        isChampion: false,
        region: 'GB',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '37',
        name: 'Ava Knight',
        weightClass: 'Flyweight',
        sport: 'Boxing',
        hypeScore: 58.4,
        momentumScore: 64.2,
        globalScore: 59.1,
        wins: 19,
        losses: 4,
        isChampion: false,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '38',
        name: 'Dakota Ditcheva',
        weightClass: 'Flyweight',
        sport: 'MMA',
        hypeScore: 72.0,
        momentumScore: 84.5,
        globalScore: 73.1,
        wins: 14,
        losses: 0,
        isChampion: false,
        region: 'GB',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '39',
        name: 'Ham Seo-hee',
        weightClass: 'Strawweight',
        sport: 'MMA',
        hypeScore: 60.5,
        momentumScore: 62.8,
        globalScore: 60.1,
        wins: 26,
        losses: 8,
        isChampion: false,
        region: 'KR',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '40',
        name: 'Dangkhongfah Banchamek',
        weightClass: 'Flyweight',
        sport: 'Muay Thai',
        hypeScore: 63.8,
        momentumScore: 70.1,
        globalScore: 64.5,
        wins: 35,
        losses: 8,
        isChampion: false,
        region: 'TH',
        gender: 'F',
      ),

      // ── ADDITIONAL MEN — Expanded roster ───────────────────────
      const GlobalRankEntry(
        id: '41',
        name: 'Islam Makhachev',
        weightClass: 'Lightweight',
        sport: 'MMA',
        hypeScore: 96.2,
        momentumScore: 94.1,
        globalScore: 95.8,
        wins: 26,
        losses: 1,
        isChampion: true,
        region: 'RU',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '42',
        name: 'Leon Edwards',
        weightClass: 'Welterweight',
        sport: 'MMA',
        hypeScore: 88.5,
        momentumScore: 82.3,
        globalScore: 85.1,
        wins: 22,
        losses: 3,
        isChampion: true,
        region: 'GB',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '43',
        name: 'Sean O\'Malley',
        weightClass: 'Bantamweight',
        sport: 'MMA',
        hypeScore: 92.1,
        momentumScore: 87.6,
        globalScore: 89.4,
        wins: 18,
        losses: 1,
        isChampion: true,
        region: 'US',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '44',
        name: 'Ilia Topuria',
        weightClass: 'Featherweight',
        sport: 'MMA',
        hypeScore: 94.8,
        momentumScore: 96.2,
        globalScore: 94.1,
        wins: 15,
        losses: 0,
        isChampion: true,
        region: 'ES',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '45',
        name: 'Dricus Du Plessis',
        weightClass: 'Middleweight',
        sport: 'MMA',
        hypeScore: 89.3,
        momentumScore: 93.5,
        globalScore: 90.2,
        wins: 22,
        losses: 2,
        isChampion: true,
        region: 'ZA',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '46',
        name: 'Jon Jones',
        weightClass: 'Heavyweight',
        sport: 'MMA',
        hypeScore: 97.0,
        momentumScore: 78.4,
        globalScore: 90.6,
        wins: 27,
        losses: 1,
        isChampion: true,
        region: 'US',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '47',
        name: 'Tom Aspinall',
        weightClass: 'Heavyweight',
        sport: 'MMA',
        hypeScore: 91.4,
        momentumScore: 95.0,
        globalScore: 92.3,
        wins: 14,
        losses: 3,
        isChampion: false,
        region: 'GB',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '48',
        name: 'Max Holloway',
        weightClass: 'Featherweight',
        sport: 'MMA',
        hypeScore: 93.6,
        momentumScore: 88.9,
        globalScore: 90.1,
        wins: 25,
        losses: 7,
        isChampion: false,
        region: 'US',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '49',
        name: 'Canelo Alvarez',
        weightClass: 'Super Middleweight',
        sport: 'Boxing',
        hypeScore: 97.8,
        momentumScore: 82.1,
        globalScore: 92.4,
        wins: 61,
        losses: 2,
        isChampion: true,
        region: 'MX',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '50',
        name: 'Terence Crawford',
        weightClass: 'Welterweight',
        sport: 'Boxing',
        hypeScore: 95.3,
        momentumScore: 90.7,
        globalScore: 93.8,
        wins: 40,
        losses: 0,
        isChampion: true,
        region: 'US',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '51',
        name: 'Naoya Inoue',
        weightClass: 'Bantamweight',
        sport: 'Boxing',
        hypeScore: 96.4,
        momentumScore: 94.8,
        globalScore: 95.2,
        wins: 27,
        losses: 0,
        isChampion: true,
        region: 'JP',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '52',
        name: 'Oleksandr Usyk',
        weightClass: 'Heavyweight',
        sport: 'Boxing',
        hypeScore: 95.1,
        momentumScore: 92.3,
        globalScore: 94.0,
        wins: 22,
        losses: 0,
        isChampion: true,
        region: 'UA',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '53',
        name: 'Tyson Fury',
        weightClass: 'Heavyweight',
        sport: 'Boxing',
        hypeScore: 96.7,
        momentumScore: 75.3,
        globalScore: 88.5,
        wins: 34,
        losses: 1,
        isChampion: false,
        region: 'GB',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '54',
        name: 'Gervonta Davis',
        weightClass: 'Lightweight',
        sport: 'Boxing',
        hypeScore: 94.2,
        momentumScore: 89.8,
        globalScore: 91.7,
        wins: 30,
        losses: 0,
        isChampion: true,
        region: 'US',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '55',
        name: 'Buakaw Banchamek',
        weightClass: 'Welterweight',
        sport: 'Muay Thai',
        hypeScore: 91.5,
        momentumScore: 70.2,
        globalScore: 82.8,
        wins: 241,
        losses: 24,
        isChampion: false,
        region: 'TH',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '56',
        name: 'Rodtang Jitmuangnon',
        weightClass: 'Flyweight',
        sport: 'Muay Thai',
        hypeScore: 93.8,
        momentumScore: 91.4,
        globalScore: 92.0,
        wins: 272,
        losses: 42,
        isChampion: true,
        region: 'TH',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '57',
        name: 'Tawanchai PK Saenchai',
        weightClass: 'Featherweight',
        sport: 'Muay Thai',
        hypeScore: 88.7,
        momentumScore: 92.5,
        globalScore: 89.3,
        wins: 132,
        losses: 32,
        isChampion: true,
        region: 'TH',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '58',
        name: 'Rico Verhoeven',
        weightClass: 'Heavyweight',
        sport: 'Kickboxing',
        hypeScore: 90.3,
        momentumScore: 85.6,
        globalScore: 88.4,
        wins: 58,
        losses: 10,
        isChampion: true,
        region: 'NL',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '59',
        name: 'Artur Beterbiev',
        weightClass: 'Light Heavyweight',
        sport: 'Boxing',
        hypeScore: 93.1,
        momentumScore: 91.0,
        globalScore: 92.5,
        wins: 20,
        losses: 0,
        isChampion: true,
        region: 'RU',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '60',
        name: 'Merab Dvalishvili',
        weightClass: 'Bantamweight',
        sport: 'MMA',
        hypeScore: 84.2,
        momentumScore: 90.8,
        globalScore: 86.1,
        wins: 18,
        losses: 4,
        isChampion: true,
        region: 'GE',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '61',
        name: 'Charles Oliveira',
        weightClass: 'Lightweight',
        sport: 'MMA',
        hypeScore: 91.0,
        momentumScore: 84.7,
        globalScore: 87.2,
        wins: 34,
        losses: 10,
        isChampion: false,
        region: 'BR',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '62',
        name: 'Kamaru Usman',
        weightClass: 'Welterweight',
        sport: 'MMA',
        hypeScore: 87.8,
        momentumScore: 72.1,
        globalScore: 80.5,
        wins: 20,
        losses: 4,
        isChampion: false,
        region: 'NG',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '63',
        name: 'Conor McGregor',
        weightClass: 'Lightweight',
        sport: 'MMA',
        hypeScore: 98.5,
        momentumScore: 65.0,
        globalScore: 82.3,
        wins: 22,
        losses: 6,
        isChampion: false,
        region: 'IE',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '64',
        name: 'Dustin Poirier',
        weightClass: 'Lightweight',
        sport: 'MMA',
        hypeScore: 89.4,
        momentumScore: 76.3,
        globalScore: 82.8,
        wins: 30,
        losses: 8,
        isChampion: false,
        region: 'US',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '65',
        name: 'Khamzat Chimaev',
        weightClass: 'Middleweight',
        sport: 'MMA',
        hypeScore: 93.7,
        momentumScore: 88.2,
        globalScore: 90.1,
        wins: 13,
        losses: 0,
        isChampion: false,
        region: 'SE',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '66',
        name: 'Devin Haney',
        weightClass: 'Super Lightweight',
        sport: 'Boxing',
        hypeScore: 86.4,
        momentumScore: 74.8,
        globalScore: 80.9,
        wins: 31,
        losses: 1,
        isChampion: false,
        region: 'US',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '67',
        name: 'Teofimo Lopez',
        weightClass: 'Super Lightweight',
        sport: 'Boxing',
        hypeScore: 85.2,
        momentumScore: 82.5,
        globalScore: 83.1,
        wins: 20,
        losses: 1,
        isChampion: true,
        region: 'US',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '68',
        name: 'Mike Perry',
        weightClass: 'Welterweight',
        sport: 'Bare Knuckle',
        hypeScore: 88.1,
        momentumScore: 85.3,
        globalScore: 85.9,
        wins: 5,
        losses: 0,
        isChampion: true,
        region: 'US',
        gender: 'M',
      ),
      const GlobalRankEntry(
        id: '69',
        name: 'Jason Knight',
        weightClass: 'Featherweight',
        sport: 'Bare Knuckle',
        hypeScore: 76.3,
        momentumScore: 79.8,
        globalScore: 77.2,
        wins: 4,
        losses: 3,
        isChampion: false,
        region: 'US',
        gender: 'M',
      ),

      // ── ADDITIONAL WOMEN — Expanded roster ─────────────────────
      const GlobalRankEntry(
        id: '70',
        name: 'Amanda Serrano',
        weightClass: 'Featherweight',
        sport: 'Boxing',
        hypeScore: 94.6,
        momentumScore: 91.2,
        globalScore: 93.1,
        wins: 47,
        losses: 2,
        isChampion: true,
        region: 'PR',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '71',
        name: 'Chantelle Cameron',
        weightClass: 'Super Lightweight',
        sport: 'Boxing',
        hypeScore: 85.3,
        momentumScore: 88.7,
        globalScore: 86.2,
        wins: 18,
        losses: 1,
        isChampion: true,
        region: 'GB',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '72',
        name: 'Seniesa Estrada',
        weightClass: 'Minimumweight',
        sport: 'Boxing',
        hypeScore: 80.1,
        momentumScore: 83.4,
        globalScore: 80.8,
        wins: 24,
        losses: 0,
        isChampion: true,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '73',
        name: 'Ebanie Bridges',
        weightClass: 'Bantamweight',
        sport: 'Boxing',
        hypeScore: 87.9,
        momentumScore: 84.6,
        globalScore: 85.3,
        wins: 10,
        losses: 1,
        isChampion: true,
        region: 'AU',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '74',
        name: 'Rose Namajunas',
        weightClass: 'Flyweight',
        sport: 'MMA',
        hypeScore: 86.4,
        momentumScore: 78.2,
        globalScore: 81.9,
        wins: 12,
        losses: 6,
        isChampion: false,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '75',
        name: 'Julianna Pena',
        weightClass: 'Bantamweight',
        sport: 'MMA',
        hypeScore: 83.7,
        momentumScore: 76.8,
        globalScore: 79.5,
        wins: 12,
        losses: 5,
        isChampion: false,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '76',
        name: 'Manon Fiorot',
        weightClass: 'Flyweight',
        sport: 'MMA',
        hypeScore: 82.5,
        momentumScore: 88.9,
        globalScore: 84.1,
        wins: 12,
        losses: 1,
        isChampion: false,
        region: 'FR',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '77',
        name: 'Kayla Harrison',
        weightClass: 'Bantamweight',
        sport: 'MMA',
        hypeScore: 88.6,
        momentumScore: 85.1,
        globalScore: 86.4,
        wins: 17,
        losses: 1,
        isChampion: false,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '78',
        name: 'Erin Blanchfield',
        weightClass: 'Flyweight',
        sport: 'MMA',
        hypeScore: 78.3,
        momentumScore: 86.7,
        globalScore: 80.2,
        wins: 12,
        losses: 2,
        isChampion: false,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '79',
        name: 'Yan Xiaonan',
        weightClass: 'Strawweight',
        sport: 'MMA',
        hypeScore: 77.1,
        momentumScore: 82.4,
        globalScore: 78.5,
        wins: 18,
        losses: 4,
        isChampion: false,
        region: 'CN',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '80',
        name: 'Alyse Anderson',
        weightClass: 'Strawweight',
        sport: 'MMA',
        hypeScore: 68.4,
        momentumScore: 77.1,
        globalScore: 70.3,
        wins: 8,
        losses: 3,
        isChampion: false,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '81',
        name: 'Janet Todd',
        weightClass: 'Bantamweight',
        sport: 'Muay Thai',
        hypeScore: 82.8,
        momentumScore: 80.5,
        globalScore: 81.2,
        wins: 5,
        losses: 3,
        isChampion: true,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '82',
        name: 'Smilla Sundell',
        weightClass: 'Strawweight',
        sport: 'Muay Thai',
        hypeScore: 79.6,
        momentumScore: 87.3,
        globalScore: 82.1,
        wins: 8,
        losses: 1,
        isChampion: true,
        region: 'SE',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '83',
        name: 'Paige VanZant',
        weightClass: 'Flyweight',
        sport: 'Bare Knuckle',
        hypeScore: 89.5,
        momentumScore: 71.2,
        globalScore: 78.8,
        wins: 1,
        losses: 2,
        isChampion: false,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '84',
        name: 'Charisa Sigala',
        weightClass: 'Bantamweight',
        sport: 'Bare Knuckle',
        hypeScore: 74.8,
        momentumScore: 80.3,
        globalScore: 76.1,
        wins: 4,
        losses: 1,
        isChampion: true,
        region: 'US',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '85',
        name: 'Skye Nicolson',
        weightClass: 'Featherweight',
        sport: 'Boxing',
        hypeScore: 85.7,
        momentumScore: 88.9,
        globalScore: 86.4,
        wins: 13,
        losses: 0,
        isChampion: true,
        region: 'AU',
        gender: 'F',
      ),
      const GlobalRankEntry(
        id: '86',
        name: 'Joseph Parker',
        weightClass: 'Heavyweight',
        sport: 'Boxing',
        hypeScore: 87.3,
        momentumScore: 82.6,
        globalScore: 84.8,
        wins: 35,
        losses: 3,
        isChampion: false,
        region: 'NZ',
        gender: 'M',
      ),
    ];
  }
}

/// A single entry in the global ranking leaderboard.
class GlobalRankEntry {
  final String id;
  final String name;
  final String weightClass;
  final String sport;
  final double hypeScore;
  final double momentumScore;
  final double globalScore;
  final int wins;
  final int losses;
  final bool isChampion;
  final String region;
  final String gender; // 'M' or 'F'

  const GlobalRankEntry({
    required this.id,
    required this.name,
    required this.weightClass,
    required this.sport,
    required this.hypeScore,
    required this.momentumScore,
    required this.globalScore,
    required this.wins,
    required this.losses,
    required this.isChampion,
    required this.region,
    required this.gender,
  });

  String get record => '$wins-$losses';
}
