apiVersion: v1
kind: Service
metadata:
  name: my-backend-metrics
  namespace: default
  labels:
    app: my-backend
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  selector:
    app: my-backend
