import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:equatable/equatable.dart';

/// ═══════════════════════════════════════════════════════════════════════════
/// SOCIAL CLIP MODEL — Viral Moment Metadata
/// ═══════════════════════════════════════════════════════════════════════════
///
/// This is the metadata backbone for every viral moment in DFC.
/// Every knockdown, submission, round end, or broadcast marker becomes a clip.
///
/// Engagement Metrics:
///   - views: Raw clip views
///   - likes: Engagement signal
///   - shares: Virality multiplier
///   - comments: Community signal
///   - ppvConversions: Revenue signal (highest weight)
///   - trendingScore: Calculated virality ranking
///
/// Firestore Path:
///   ppv_events/{eventId}/event_sessions/{sessionId}/social_clips/{clipId}
///
/// ═══════════════════════════════════════════════════════════════════════════

enum ClipType {
  knockdown, // Instant impact moment
  submission, // Submission finish
  roundEnd, // Round summary
  highlight, // Multi-moment highlight
  comeback, // Momentum swing
  statsReel, // Stats-focused
}

extension ClipTypeExt on ClipType {
  String get label {
    switch (this) {
      case ClipType.knockdown:
        return 'Knockdown';
      case ClipType.submission:
        return 'Submission';
      case ClipType.roundEnd:
        return 'Round End';
      case ClipType.highlight:
        return 'Highlight';
      case ClipType.comeback:
        return 'Comeback';
      case ClipType.statsReel:
        return 'Stats Reel';
    }
  }

  String get emoji {
    switch (this) {
      case ClipType.knockdown:
        return '💥';
      case ClipType.submission:
        return '🔐';
      case ClipType.roundEnd:
        return '🔔';
      case ClipType.highlight:
        return '⭐';
      case ClipType.comeback:
        return '🔥';
      case ClipType.statsReel:
        return '📊';
    }
  }
}

/// Engagement metrics for a clip
class ClipEngagement extends Equatable {
  final int views;
  final int likes;
  final int shares;
  final int comments;
  final int ppvConversions;

  const ClipEngagement({
    this.views = 0,
    this.likes = 0,
    this.shares = 0,
    this.comments = 0,
    this.ppvConversions = 0,
  });

  /// Calculate trending score based on engagement
  /// Formula: views * 0.3 + likes * 0.4 + shares * 1.0 + ppvConversions * 2.0
  double calculateTrendingScore() {
    return (views * 0.3) +
        (likes * 0.4) +
        (shares * 1.0) +
        (ppvConversions * 2.0);
  }

  ClipEngagement copyWith({
    int? views,
    int? likes,
    int? shares,
    int? comments,
    int? ppvConversions,
  }) {
    return ClipEngagement(
      views: views ?? this.views,
      likes: likes ?? this.likes,
      shares: shares ?? this.shares,
      comments: comments ?? this.comments,
      ppvConversions: ppvConversions ?? this.ppvConversions,
    );
  }

  Map<String, dynamic> toFirestore() => {
    'views': views,
    'likes': likes,
    'shares': shares,
    'comments': comments,
    'ppvConversions': ppvConversions,
  };

  factory ClipEngagement.fromFirestore(Map<String, dynamic> data) {
    return ClipEngagement(
      views: data['views'] as int? ?? 0,
      likes: data['likes'] as int? ?? 0,
      shares: data['shares'] as int? ?? 0,
      comments: data['comments'] as int? ?? 0,
      ppvConversions: data['ppvConversions'] as int? ?? 0,
    );
  }

  @override
  List<Object?> get props => [views, likes, shares, comments, ppvConversions];
}

/// Social Clip — The atom of DFC's social layer
class SocialClip extends Equatable {
  /// Unique clip ID
  final String id;

  /// Event context
  final String eventId;
  final String sessionId;
  final String fightId;

  /// Source — what triggered this clip?
  final ClipType clipType;
  final String? sourceMarkerId; // Links to BroadcastReplayMarker
  final String? sourceEventId; // Links to Fight Event

  /// Clip Content
  final String videoUrl;
  final String? thumbnailUrl;
  final int durationSeconds;
  final int startTimeInFight; // Seconds from fight start

  /// Fight Context
  final String fighter1Id;
  final String fighter1Name;
  final String fighter2Id;
  final String fighter2Name;
  final int round;

  /// Metadata
  final String title;
  final String? description;
  final bool autoGenerated; // true if created by AutoClipGeneratorService
  final String? creatorId; // null if auto-generated, set if creator reaction

  /// Engagement
  final ClipEngagement engagement;

  /// Trending
  final double trendingScore;
  final DateTime createdAt;
  final DateTime? updatedAt;

  const SocialClip({
    required this.id,
    required this.eventId,
    required this.sessionId,
    required this.fightId,
    required this.clipType,
    this.sourceMarkerId,
    this.sourceEventId,
    required this.videoUrl,
    this.thumbnailUrl,
    required this.durationSeconds,
    required this.startTimeInFight,
    required this.fighter1Id,
    required this.fighter1Name,
    required this.fighter2Id,
    required this.fighter2Name,
    required this.round,
    required this.title,
    this.description,
    this.autoGenerated = true,
    this.creatorId,
    this.engagement = const ClipEngagement(),
    this.trendingScore = 0.0,
    required this.createdAt,
    this.updatedAt,
  });

  /// Get display title with emoji
  String get displayTitle => '${clipType.emoji} ${clipType.label}';

  /// Is this clip trending? (arbitrary threshold)
  bool get isTrending => trendingScore > 100.0;

  /// Format view count (e.g., "1.2K", "5M")
  String get formattedViews {
    final views = engagement.views;
    if (views >= 1000000) {
      return '${(views / 1000000).toStringAsFixed(1)}M';
    } else if (views >= 1000) {
      return '${(views / 1000).toStringAsFixed(1)}K';
    }
    return views.toString();
  }

  SocialClip copyWith({
    String? id,
    String? eventId,
    String? sessionId,
    String? fightId,
    ClipType? clipType,
    String? sourceMarkerId,
    String? sourceEventId,
    String? videoUrl,
    String? thumbnailUrl,
    int? durationSeconds,
    int? startTimeInFight,
    String? fighter1Id,
    String? fighter1Name,
    String? fighter2Id,
    String? fighter2Name,
    int? round,
    String? title,
    String? description,
    bool? autoGenerated,
    String? creatorId,
    ClipEngagement? engagement,
    double? trendingScore,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return SocialClip(
      id: id ?? this.id,
      eventId: eventId ?? this.eventId,
      sessionId: sessionId ?? this.sessionId,
      fightId: fightId ?? this.fightId,
      clipType: clipType ?? this.clipType,
      sourceMarkerId: sourceMarkerId ?? this.sourceMarkerId,
      sourceEventId: sourceEventId ?? this.sourceEventId,
      videoUrl: videoUrl ?? this.videoUrl,
      thumbnailUrl: thumbnailUrl ?? this.thumbnailUrl,
      durationSeconds: durationSeconds ?? this.durationSeconds,
      startTimeInFight: startTimeInFight ?? this.startTimeInFight,
      fighter1Id: fighter1Id ?? this.fighter1Id,
      fighter1Name: fighter1Name ?? this.fighter1Name,
      fighter2Id: fighter2Id ?? this.fighter2Id,
      fighter2Name: fighter2Name ?? this.fighter2Name,
      round: round ?? this.round,
      title: title ?? this.title,
      description: description ?? this.description,
      autoGenerated: autoGenerated ?? this.autoGenerated,
      creatorId: creatorId ?? this.creatorId,
      engagement: engagement ?? this.engagement,
      trendingScore: trendingScore ?? this.trendingScore,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'id': id,
      'eventId': eventId,
      'sessionId': sessionId,
      'fightId': fightId,
      'clipType': clipType.toString().split('.').last,
      'sourceMarkerId': sourceMarkerId,
      'sourceEventId': sourceEventId,
      'videoUrl': videoUrl,
      'thumbnailUrl': thumbnailUrl,
      'durationSeconds': durationSeconds,
      'startTimeInFight': startTimeInFight,
      'fighter1Id': fighter1Id,
      'fighter1Name': fighter1Name,
      'fighter2Id': fighter2Id,
      'fighter2Name': fighter2Name,
      'round': round,
      'title': title,
      'description': description,
      'autoGenerated': autoGenerated,
      'creatorId': creatorId,
      'engagement': engagement.toFirestore(),
      'trendingScore': trendingScore,
      'createdAt': createdAt,
      'updatedAt': updatedAt ?? DateTime.now(),
    };
  }

  factory SocialClip.fromFirestore(Map<String, dynamic> data, String docId) {
    return SocialClip(
      id: docId,
      eventId: data['eventId'] as String? ?? '',
      sessionId: data['sessionId'] as String? ?? '',
      fightId: data['fightId'] as String? ?? '',
      clipType: _parseClipType(data['clipType'] as String? ?? 'highlight'),
      sourceMarkerId: data['sourceMarkerId'] as String?,
      sourceEventId: data['sourceEventId'] as String?,
      videoUrl: data['videoUrl'] as String? ?? '',
      thumbnailUrl: data['thumbnailUrl'] as String?,
      durationSeconds: data['durationSeconds'] as int? ?? 0,
      startTimeInFight: data['startTimeInFight'] as int? ?? 0,
      fighter1Id: data['fighter1Id'] as String? ?? '',
      fighter1Name: data['fighter1Name'] as String? ?? '',
      fighter2Id: data['fighter2Id'] as String? ?? '',
      fighter2Name: data['fighter2Name'] as String? ?? '',
      round: data['round'] as int? ?? 1,
      title: data['title'] as String? ?? '',
      description: data['description'] as String?,
      autoGenerated: data['autoGenerated'] as bool? ?? true,
      creatorId: data['creatorId'] as String?,
      engagement: ClipEngagement.fromFirestore(
        data['engagement'] as Map<String, dynamic>? ?? {},
      ),
      trendingScore: (data['trendingScore'] as num?)?.toDouble() ?? 0.0,
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      updatedAt: (data['updatedAt'] as Timestamp?)?.toDate(),
    );
  }

  @override
  List<Object?> get props => [
    id,
    eventId,
    sessionId,
    fightId,
    clipType,
    sourceMarkerId,
    videoUrl,
    fighter1Id,
    fighter2Id,
    trendingScore,
    createdAt,
  ];
}

/// Parse ClipType from string
ClipType _parseClipType(String value) {
  switch (value) {
    case 'knockdown':
      return ClipType.knockdown;
    case 'submission':
      return ClipType.submission;
    case 'roundEnd':
      return ClipType.roundEnd;
    case 'highlight':
      return ClipType.highlight;
    case 'comeback':
      return ClipType.comeback;
    case 'statsReel':
      return ClipType.statsReel;
    default:
      return ClipType.highlight;
  }
}
