/**
 * DFC Extended Seed: Fighters + Fight Cards + Live Fights
 * Run: node scripts/seed_fighters_and_fights.cjs --key=<path>
 *
 * Seeds:
 *   fighters/{id}           - 10 real fighter profiles
 *   ppv_events/{id}         - updates fightCard arrays on existing PPV events
 *   live_fights/{id}        - one live fight for scoring screen
 */
"use strict";

const admin = require("firebase-admin");
const path = require("path");

// ── Credential resolution ─────────────────────────────────────────────────
const keyArg = process.argv.find((a) => a.startsWith("--key="));
if (keyArg) {
  const keyPath = keyArg.replace("--key=", "");
  const serviceAccount = require(path.resolve(keyPath));
  admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
} else {
  admin.initializeApp();
}

const db = admin.firestore();
const TS = admin.firestore.Timestamp;

function daysAgo(n) {
  return TS.fromDate(new Date(Date.now() - n * 86400000));
}
function daysFromNow(n) {
  return TS.fromDate(new Date(Date.now() + n * 86400000));
}

// ═══════════════════════════════════════════════════════════════════════════
// FIGHTERS — collection: fighters
// Shape matches FighterModel.toFirestore()
// ═══════════════════════════════════════════════════════════════════════════
const fighters = [
  {
    id: "fighter-della-maddalena",
    userId: "fighter-della-maddalena",
    fullName: "Jack Della Maddalena",
    nickname: "The Hunter",
    nationality: "Australian",
    gender: "male",
    weightClass: "Welterweight",
    sportType: "MMA",
    stance: "orthodox",
    status: "active",
    heightCm: 183,
    reachCm: 193,
    wins: 16,
    losses: 2,
    draws: 0,
    noContests: 0,
    knockouts: 12,
    submissions: 2,
    city: "Perth",
    state: "WA",
    country: "Australia",
    latitude: -31.9505,
    longitude: 115.8605,
    bio: "Australia's most dangerous welterweight. WA-born, world-ranked, and coming for the belt.",
    photoUrl:
      "https://firebasestorage.googleapis.com/v0/b/datafightcentral.appspot.com/o/fighters%2Fdella-maddalena.jpg?alt=media",
    coverPhotoUrl: "",
    regionId: "australia-wa",
    upcomingEventId: "ppv-ufc-327",
    matchupAvailability: "notAvailable",
    preferredWeightClasses: ["Welterweight"],
    preferredOpponentStyles: [],
    willingToTravel: true,
    minimumPurse: 0,
    blockedFighterIds: [],
    previousGymIds: [],
    socialLinks: {},
    qnaEnabled: true,
    commentsEnabled: true,
    maxTravelDistanceKm: 20000,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(1),
  },
  {
    id: "fighter-prates-renato",
    userId: "fighter-prates-renato",
    fullName: "Renato Moicano",
    nickname: "Money",
    nationality: "Brazilian",
    gender: "male",
    weightClass: "Welterweight",
    sportType: "MMA",
    stance: "orthodox",
    status: "active",
    heightCm: 178,
    reachCm: 183,
    wins: 21,
    losses: 6,
    draws: 0,
    noContests: 1,
    knockouts: 5,
    submissions: 8,
    city: "Rio de Janeiro",
    state: "",
    country: "Brazil",
    latitude: -22.9068,
    longitude: -43.1729,
    bio: "Brazilian jiu-jitsu specialist and philosopher-fighter. If you're not first, you're last.",
    photoUrl: "",
    coverPhotoUrl: "",
    regionId: "south-america",
    upcomingEventId: "ppv-ufc-327",
    matchupAvailability: "notAvailable",
    preferredWeightClasses: ["Welterweight", "Lightweight"],
    preferredOpponentStyles: [],
    willingToTravel: true,
    minimumPurse: 0,
    blockedFighterIds: [],
    previousGymIds: [],
    socialLinks: {},
    qnaEnabled: true,
    commentsEnabled: true,
    maxTravelDistanceKm: 20000,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(2),
  },
  {
    id: "fighter-alex-volkanovski",
    userId: "fighter-alex-volkanovski",
    fullName: "Alexander Volkanovski",
    nickname: "The Great",
    nationality: "Australian",
    gender: "male",
    weightClass: "Featherweight",
    sportType: "MMA",
    stance: "orthodox",
    status: "active",
    heightCm: 168,
    reachCm: 182,
    wins: 26,
    losses: 4,
    draws: 0,
    noContests: 0,
    knockouts: 12,
    submissions: 1,
    city: "Wollongong",
    state: "NSW",
    country: "Australia",
    latitude: -34.4278,
    longitude: 150.8931,
    bio: "Former UFC Featherweight Champion. Australia's greatest MMA fighter. The Great.",
    photoUrl: "",
    coverPhotoUrl: "",
    regionId: "australia-nsw",
    upcomingEventId: "ppv-ufc-328",
    matchupAvailability: "notAvailable",
    preferredWeightClasses: ["Featherweight"],
    preferredOpponentStyles: [],
    willingToTravel: true,
    minimumPurse: 0,
    blockedFighterIds: [],
    previousGymIds: [],
    socialLinks: {},
    qnaEnabled: true,
    commentsEnabled: true,
    maxTravelDistanceKm: 20000,
    createdAt: daysAgo(500),
    updatedAt: daysAgo(1),
  },
  {
    id: "fighter-rob-whittaker",
    userId: "fighter-rob-whittaker",
    fullName: "Robert Whittaker",
    nickname: "The Reaper",
    nationality: "Australian",
    gender: "male",
    weightClass: "Middleweight",
    sportType: "MMA",
    stance: "orthodox",
    status: "active",
    heightCm: 183,
    reachCm: 185,
    wins: 25,
    losses: 7,
    draws: 0,
    noContests: 0,
    knockouts: 9,
    submissions: 1,
    city: "Sydney",
    state: "NSW",
    country: "Australia",
    latitude: -33.8688,
    longitude: 151.2093,
    bio: "Former UFC Middleweight Champion. Two-time title challenger. The backbone of Australian MMA.",
    photoUrl: "",
    coverPhotoUrl: "",
    regionId: "australia-nsw",
    upcomingEventId: "ppv-ufc-328",
    matchupAvailability: "notAvailable",
    preferredWeightClasses: ["Middleweight"],
    preferredOpponentStyles: [],
    willingToTravel: true,
    minimumPurse: 0,
    blockedFighterIds: [],
    previousGymIds: [],
    socialLinks: {},
    qnaEnabled: true,
    commentsEnabled: true,
    maxTravelDistanceKm: 20000,
    createdAt: daysAgo(600),
    updatedAt: daysAgo(3),
  },
  {
    id: "fighter-tai-tuivasa",
    userId: "fighter-tai-tuivasa",
    fullName: "Tai Tuivasa",
    nickname: "Bam Bam",
    nationality: "Australian",
    gender: "male",
    weightClass: "Heavyweight",
    sportType: "MMA",
    stance: "orthodox",
    status: "active",
    heightCm: 188,
    reachCm: 193,
    wins: 15,
    losses: 7,
    draws: 0,
    noContests: 0,
    knockouts: 13,
    submissions: 0,
    city: "Mount Druitt",
    state: "NSW",
    country: "Australia",
    latitude: -33.7699,
    longitude: 150.8219,
    bio: "The Bam Bam shoey king. Most entertaining heavyweight in the game. If you mess with Bam Bam, you get rocked.",
    photoUrl: "",
    coverPhotoUrl: "",
    regionId: "australia-nsw",
    upcomingEventId: "ppv-brisbane-bonanza",
    matchupAvailability: "notAvailable",
    preferredWeightClasses: ["Heavyweight"],
    preferredOpponentStyles: [],
    willingToTravel: true,
    minimumPurse: 0,
    blockedFighterIds: [],
    previousGymIds: [],
    socialLinks: {},
    qnaEnabled: true,
    commentsEnabled: true,
    maxTravelDistanceKm: 20000,
    createdAt: daysAgo(450),
    updatedAt: daysAgo(2),
  },
  {
    id: "fighter-jake-matthews",
    userId: "fighter-jake-matthews",
    fullName: "Jake Matthews",
    nickname: "The Celtic Kid",
    nationality: "Australian",
    gender: "male",
    weightClass: "Welterweight",
    sportType: "MMA",
    stance: "southpaw",
    status: "active",
    heightCm: 183,
    reachCm: 188,
    wins: 18,
    losses: 8,
    draws: 0,
    noContests: 0,
    knockouts: 5,
    submissions: 6,
    city: "Melbourne",
    state: "VIC",
    country: "Australia",
    latitude: -37.8136,
    longitude: 144.9631,
    bio: "Melbourne's UFC veteran. 26 fights, still growing. The most experienced Australian in the UFC roster.",
    photoUrl: "",
    coverPhotoUrl: "",
    regionId: "australia-vic",
    matchupAvailability: "available",
    preferredWeightClasses: ["Welterweight"],
    preferredOpponentStyles: [],
    willingToTravel: true,
    minimumPurse: 5000,
    blockedFighterIds: [],
    previousGymIds: [],
    socialLinks: {},
    qnaEnabled: true,
    commentsEnabled: true,
    maxTravelDistanceKm: 15000,
    createdAt: daysAgo(350),
    updatedAt: daysAgo(5),
  },
  {
    id: "fighter-maddison-poblete",
    userId: "fighter-maddison-poblete",
    fullName: "Maddison Poblete",
    nickname: "Maddison",
    nationality: "Australian",
    gender: "female",
    weightClass: "Women's Strawweight",
    sportType: "MMA",
    stance: "orthodox",
    status: "active",
    heightCm: 163,
    reachCm: 165,
    wins: 7,
    losses: 4,
    draws: 0,
    noContests: 0,
    knockouts: 1,
    submissions: 4,
    city: "Brisbane",
    state: "QLD",
    country: "Australia",
    latitude: -27.4698,
    longitude: 153.0251,
    bio: "Brisbane-born UFC strawweight. Grappling specialist with iron will.",
    photoUrl: "",
    coverPhotoUrl: "",
    regionId: "australia-qld",
    matchupAvailability: "available",
    preferredWeightClasses: ["Women's Strawweight", "Women's Flyweight"],
    preferredOpponentStyles: [],
    willingToTravel: true,
    minimumPurse: 3000,
    blockedFighterIds: [],
    previousGymIds: [],
    socialLinks: {},
    qnaEnabled: true,
    commentsEnabled: true,
    maxTravelDistanceKm: 10000,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(10),
  },
  {
    id: "fighter-tyson-pedro",
    userId: "fighter-tyson-pedro",
    fullName: "Tyson Pedro",
    nickname: "The Hulk",
    nationality: "Australian",
    gender: "male",
    weightClass: "Light Heavyweight",
    sportType: "MMA",
    stance: "orthodox",
    status: "active",
    heightCm: 188,
    reachCm: 191,
    wins: 9,
    losses: 5,
    draws: 0,
    noContests: 0,
    knockouts: 5,
    submissions: 3,
    city: "Sydney",
    state: "NSW",
    country: "Australia",
    latitude: -33.8688,
    longitude: 151.2093,
    bio: "Samoan-Australian light heavyweight with knockout power in both hands. The Hulk smashes.",
    photoUrl: "",
    coverPhotoUrl: "",
    regionId: "australia-nsw",
    matchupAvailability: "notAvailable",
    preferredWeightClasses: ["Light Heavyweight"],
    preferredOpponentStyles: [],
    willingToTravel: true,
    minimumPurse: 0,
    blockedFighterIds: [],
    previousGymIds: [],
    socialLinks: {},
    qnaEnabled: true,
    commentsEnabled: true,
    maxTravelDistanceKm: 20000,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(7),
  },
  {
    id: "fighter-liam-wilson",
    userId: "fighter-liam-wilson",
    fullName: "Liam Wilson",
    nickname: "The Hard Nut",
    nationality: "Australian",
    gender: "male",
    weightClass: "Super Featherweight",
    sportType: "Boxing",
    stance: "orthodox",
    status: "active",
    heightCm: 175,
    reachCm: 178,
    wins: 12,
    losses: 3,
    draws: 0,
    noContests: 0,
    knockouts: 8,
    submissions: 0,
    city: "Brisbane",
    state: "QLD",
    country: "Australia",
    latitude: -27.4698,
    longitude: 153.0251,
    bio: "IBC Super Featherweight contender. Hard as nails from the Gold Coast.",
    photoUrl: "",
    coverPhotoUrl: "",
    regionId: "australia-qld",
    upcomingEventId: "ppv-ibc-03",
    matchupAvailability: "notAvailable",
    preferredWeightClasses: ["Super Featherweight", "Lightweight"],
    preferredOpponentStyles: [],
    willingToTravel: true,
    minimumPurse: 0,
    blockedFighterIds: [],
    previousGymIds: [],
    socialLinks: {},
    qnaEnabled: true,
    commentsEnabled: true,
    maxTravelDistanceKm: 20000,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(4),
  },
  {
    id: "fighter-jy-raja",
    userId: "fighter-jy-raja",
    fullName: "Jy Raja",
    nickname: "The Warrior King",
    nationality: "Australian",
    gender: "male",
    weightClass: "Middleweight",
    sportType: "BKFC",
    stance: "orthodox",
    status: "active",
    heightCm: 180,
    reachCm: 185,
    wins: 8,
    losses: 2,
    draws: 1,
    noContests: 0,
    knockouts: 6,
    submissions: 0,
    city: "Townsville",
    state: "QLD",
    country: "Australia",
    latitude: -19.259,
    longitude: 146.8169,
    bio: "Queensland's BKFC king. No gloves. No mercy. All warrior.",
    photoUrl: "",
    coverPhotoUrl: "",
    regionId: "australia-qld",
    upcomingEventId: "ppv-bkfc-townsville-hepi",
    matchupAvailability: "notAvailable",
    preferredWeightClasses: ["Middleweight"],
    preferredOpponentStyles: [],
    willingToTravel: true,
    minimumPurse: 0,
    blockedFighterIds: [],
    previousGymIds: [],
    socialLinks: {},
    qnaEnabled: true,
    commentsEnabled: true,
    maxTravelDistanceKm: 10000,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(6),
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// FIGHT CARDS — embedded into ppv_events
// Shape matches PPVFight in ppv_model.dart
// ═══════════════════════════════════════════════════════════════════════════
const fightCards = {
  "ppv-ufc-327": [
    {
      fighter1Name: "Jack Della Maddalena",
      fighter2Name: "Renato Moicano",
      fighter1Id: "fighter-della-maddalena",
      fighter2Id: "fighter-prates-renato",
      weightClass: "Welterweight",
      rounds: 5,
      isTitleFight: true,
      boutOrder: 1,
    },
    {
      fighter1Name: "Jake Matthews",
      fighter2Name: "TBA",
      fighter1Id: "fighter-jake-matthews",
      fighter2Id: "",
      weightClass: "Welterweight",
      rounds: 3,
      isTitleFight: false,
      boutOrder: 5,
    },
  ],
  "ppv-ufc-328": [
    {
      fighter1Name: "Alexander Volkanovski",
      fighter2Name: "TBA",
      fighter1Id: "fighter-alex-volkanovski",
      fighter2Id: "",
      weightClass: "Featherweight",
      rounds: 5,
      isTitleFight: true,
      boutOrder: 1,
    },
    {
      fighter1Name: "Robert Whittaker",
      fighter2Name: "TBA",
      fighter1Id: "fighter-rob-whittaker",
      fighter2Id: "",
      weightClass: "Middleweight",
      rounds: 5,
      isTitleFight: false,
      boutOrder: 2,
    },
  ],
  "ppv-ibc-03": [
    {
      fighter1Name: "Liam Wilson",
      fighter2Name: "TBA",
      fighter1Id: "fighter-liam-wilson",
      fighter2Id: "",
      weightClass: "Super Featherweight",
      rounds: 12,
      isTitleFight: true,
      boutOrder: 1,
    },
  ],
  "ppv-bkfc-townsville-hepi": [
    {
      fighter1Name: "Jy Raja",
      fighter2Name: "TBA",
      fighter1Id: "fighter-jy-raja",
      fighter2Id: "",
      weightClass: "Middleweight",
      rounds: 5,
      isTitleFight: false,
      boutOrder: 1,
    },
  ],
  "ppv-brisbane-bonanza": [
    {
      fighter1Name: "Tai Tuivasa",
      fighter2Name: "TBA",
      fighter1Id: "fighter-tai-tuivasa",
      fighter2Id: "",
      weightClass: "Heavyweight",
      rounds: 3,
      isTitleFight: false,
      boutOrder: 1,
    },
    {
      fighter1Name: "Jake Matthews",
      fighter2Name: "TBA",
      fighter1Id: "fighter-jake-matthews",
      fighter2Id: "",
      weightClass: "Welterweight",
      rounds: 3,
      isTitleFight: false,
      boutOrder: 2,
    },
    {
      fighter1Name: "Maddison Poblete",
      fighter2Name: "TBA",
      fighter1Id: "fighter-maddison-poblete",
      fighter2Id: "",
      weightClass: "Women's Strawweight",
      rounds: 3,
      isTitleFight: false,
      boutOrder: 3,
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════
// LIVE FIGHTS — collection: live_fights
// For scoring screen (defaults to this ID)
// ═══════════════════════════════════════════════════════════════════════════
const liveFights = [
  {
    id: "ibc-03-gold-coast", // matches hardcoded default in live_scoring_screen.dart
    eventId: "ppv-ibc-03",
    eventName: "IBC 03 — International Boxing Championships",
    fighter1Id: "fighter-liam-wilson",
    fighter1Name: "Liam Wilson",
    fighter1Nickname: "The Hard Nut",
    fighter2Id: "fighter-unknown-opponent",
    fighter2Name: "TBA",
    fighter2Nickname: "",
    weightClass: "Super Featherweight",
    totalRounds: 12,
    currentRound: 0,
    status: "scheduled", // scheduled | live | ended
    isTitleFight: true,
    venue: "Gold Coast Convention Centre",
    city: "Gold Coast",
    country: "Australia",
    scheduledDate: daysFromNow(21),
    createdAt: TS.now(),
  },
  {
    id: "eternal-88-bout-1",
    eventId: "ppv-eternal88",
    eventName: "Eternal MMA 88 — Brisbane",
    fighter1Id: "fighter-jake-matthews",
    fighter1Name: "Jake Matthews",
    fighter1Nickname: "The Celtic Kid",
    fighter2Id: "fighter-unknown-opponent",
    fighter2Name: "TBA",
    fighter2Nickname: "",
    weightClass: "Welterweight",
    totalRounds: 3,
    currentRound: 0,
    status: "scheduled",
    isTitleFight: false,
    venue: "Brisbane Entertainment Centre",
    city: "Brisbane",
    country: "Australia",
    scheduledDate: daysFromNow(7),
    createdAt: TS.now(),
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// SEED
// ═══════════════════════════════════════════════════════════════════════════
async function seed() {
  // ── Fighters ─────────────────────────────────────────────────────────────
  console.log(`Seeding ${fighters.length} fighters...`);
  const fighterBatch = db.batch();
  for (const f of fighters) {
    const { id, ...data } = f;
    fighterBatch.set(db.collection("fighters").doc(id), data, { merge: true });
  }
  await fighterBatch.commit();
  console.log("✅ fighters seeded");

  // ── Fight Cards (update ppv_events) ──────────────────────────────────────
  console.log(
    `Updating ${Object.keys(fightCards).length} ppv_events with fight cards...`,
  );
  const cardBatch = db.batch();
  for (const [ppvId, card] of Object.entries(fightCards)) {
    cardBatch.update(db.collection("ppv_events").doc(ppvId), {
      fightCard: card,
    });
  }
  await cardBatch.commit();
  console.log("✅ fight cards embedded into ppv_events");

  // ── Live Fights ───────────────────────────────────────────────────────────
  console.log(`Seeding ${liveFights.length} live_fights...`);
  const liveBatch = db.batch();
  for (const lf of liveFights) {
    const { id, ...data } = lf;
    liveBatch.set(db.collection("live_fights").doc(id), data, { merge: true });
  }
  await liveBatch.commit();
  console.log("✅ live_fights seeded");

  console.log("\n🔥 Fighters, fight cards, and live fights are live.");
  console.log("   Fighter profiles will now show real data.");
  console.log("   PPV event cards will now show fight card listings.");
  console.log("   Scoring screen IBC-03 default will resolve.");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
