events { }
http {
  server {
    listen 80;
    server_name _;

    location /api/ {
      proxy_pass http://ingest:8000/;
      proxy_set_header Host $host;
    }

    location /entitlements/ {
      proxy_pass http://entitlements:4010/;
      proxy_set_header Host $host;
    }

    location /predictor/ {
      proxy_pass http://predictor:8090/;
      proxy_set_header Host $host;
    }
  }
}
