import 'package:flutter/painting.dart';
import 'package:flutter/widgets.dart';
import '../utils/image_url_sanitizer.dart';

/// Image asset paths for Data Fight Central.
///
/// ALL placeholders use local DFC-branded assets — never external stock URLs.
/// When real content arrives from Firestore/APIs with verified URLs, those
/// take priority. These are ONLY the fallbacks for demo / seeded content.
class ImageAssets {
  ImageAssets._();

  // ── Core brand assets ──────────────────────────────────────────────────
  static const String dfcBrandedPlaceholder = 'assets/logos/dfc_hex_badge.png';
  static const String dfcHeroBg =
      'assets/logos/DFC logo with cyan glow effect.png';
  static const String dfcLogoGlow =
      'assets/logos/DFC logo with cyan glow effect.png';
  static const String dfcWordmark = 'assets/logos/dfc_wordmark.png';
  static const String dfcIcon = 'assets/logos/dfc_icon_transparent.png';
  static const String dfcAppIcon = 'assets/logos/dfc_app_icon.png';

  // ── Branded backgrounds (distinct visuals per context) ─────────────────
  static const String bgHero = 'assets/dfc_backgrounds/dfc_and_back_ground.png';
  static const String bgAction = 'assets/dfc_backgrounds/new_dfc_image_1.png';
  static const String bgEvent = 'assets/dfc_backgrounds/dfc2_image_.png';
  static const String bgPromo = 'assets/dfc_backgrounds/dfc2_image.png';
  static const String bgLogo1024 =
      'assets/dfc_backgrounds/datafight_central_with_logo.png';
  static const String bgLogoSmall = 'assets/dfc_backgrounds/datafightlogo.png';
  static const String bgCentral =
      'assets/dfc_backgrounds/datafight_central_with_logo.png';
  static const String bgResized = 'assets/dfc_backgrounds/dfc_logo_resized.png';
  static const String bgSquare = 'assets/dfc_backgrounds/dfc_logo_resized.png';

  // ── Sport-specific (use distinct backgrounds so pages don't all look the same)
  static const String ufcPlaceholder = bgAction;
  static const String boxingPlaceholder = bgEvent;
  static const String kickboxingPlaceholder = bgPromo;
  static const String bkfcPlaceholder = bgHero;
  static const String muayThaiPlaceholder = bgCentral;

  // ── Domain placeholders (each context gets a different visual) ─────────
  static const String fightPlaceholder = bgAction;
  static const String trainingPlaceholder = bgEvent;
  static const String wellnessPlaceholder = bgResized;
  static const String eventPlaceholder = bgPromo;
  static const String mapPlaceholder = bgLogo1024;
  static const String userPlaceholder = dfcBrandedPlaceholder;
  static const String nutritionPlaceholder = bgSquare;
  static const String gymPlaceholder = bgCentral;

  // ── Social feed cards (rotate 4 different looks) ──────────────────────
  static const String socialPost1 = bgAction;
  static const String socialPost2 = bgEvent;
  static const String socialPost3 = bgPromo;
  static const String socialPost4 = bgCentral;

  // Training / Wellness / Map
  static const String trainingSession = bgAction;
  static const String wellnessActivity = bgResized;
  static const String globalMapPreview = bgLogo1024;

  // ── Group photo ────────────────────────────────────────────────────────
  static const String legendsGroupPhoto =
      'assets/dfc_backgrounds/dfc_and_back_ground.png';

  // ── PPV poster assets (generated by tools/generate_ppv_posters_gritty) ─
  static const String _ppvDir = 'assets/ppv';

  // Per-event hero posters (1600×2400)
  static const String ppvUfcPerth2026Hero =
      '$_ppvDir/ppv-ufc-perth-2026_hero.jpg';
  static const String ppvIbc03Hero = '$_ppvDir/ppv-ibc-03_hero.jpg';
  static const String ppvEternal80Hero = '$_ppvDir/ppv-eternal-80_hero.jpg';
  static const String ppvEliteFsCairnsHero =
      '$_ppvDir/ppv-elite-fs-cairns_hero.jpg';
  static const String ppvUltimateLegends2026Hero =
      '$_ppvDir/ppv-ultimate-legends-apr-2026_hero.jpg';
  static const String ppvUfc327Hero = '$_ppvDir/ppv-ufc-327_hero.jpg';
  static const String ppvUfc328Hero = '$_ppvDir/ppv-ufc-328_hero.jpg';
  static const String ppvPflPittsburgh2026Hero =
      '$_ppvDir/ppv-pfl-pittsburgh-2026_hero.jpg';
  static const String ppvBkfc72Hero = '$_ppvDir/ppv-bkfc-72_hero.jpg';
  static const String ppvOne170Hero = '$_ppvDir/ppv-one-170_hero.jpg';
  static const String ppvHex25Hero = '$_ppvDir/ppv-hex-25_hero.jpg';
  static const String ppvBkfcTownsvilleHepiHero =
      '$_ppvDir/ppv-bkfc-townsville-hepi_hero.jpg';
  static const String ppvBkfcNewcastleHero =
      '$_ppvDir/ppv-bkfc-newcastle_hero.jpg';
  static const String ppvIfmaAntalyacupHero =
      '$_ppvDir/ppv-ifma-antalyacup_hero.jpg';
  static const String ppvLegends45Hero = '$_ppvDir/ppv-legends45_hero.jpg';
  static const String ppvEternal88Hero = '$_ppvDir/ppv-eternal88_hero.jpg';
  static const String ppvAdelaideCs12Hero =
      '$_ppvDir/ppv-adelaide-cs12_hero.jpg';
  static const String ppvUfcParamountFightnightHero =
      '$_ppvDir/ppv-ufc-paramount-fightnight_hero.jpg';
  static const String ppvBrisbaneBonanzaHero =
      '$_ppvDir/ppv-brisbane-bonanza_hero.jpg';
  static const String ppvWestcoastWarriors33Hero =
      '$_ppvDir/ppv-westcoast-warriors33_hero.jpg';

  // Per-event banners (1600×900)
  static const String ppvUfcPerth2026Banner =
      '$_ppvDir/ppv-ufc-perth-2026_banner.jpg';
  static const String ppvIbc03Banner = '$_ppvDir/ppv-ibc-03_banner.jpg';
  static const String ppvBkfc72Banner = '$_ppvDir/ppv-bkfc-72_banner.jpg';
  static const String ppvHex25Banner = '$_ppvDir/ppv-hex-25_banner.jpg';
  static const String ppvUltimateLegends2026Banner =
      '$_ppvDir/ppv-ultimate-legends-apr-2026_banner.jpg';
  static const String ppvBkfcTownsvilleHepiBanner =
      '$_ppvDir/ppv-bkfc-townsville-hepi_banner.jpg';
  static const String ppvLegends45Banner = '$_ppvDir/ppv-legends45_banner.jpg';
  static const String ppvEternal88Banner = '$_ppvDir/ppv-eternal88_banner.jpg';
  static const String ppvAdelaideCs12Banner =
      '$_ppvDir/ppv-adelaide-cs12_banner.jpg';
  static const String ppvUfcParamountFightnightBanner =
      '$_ppvDir/ppv-ufc-paramount-fightnight_banner.jpg';

  // Per-event thumbnails (1200×1200)
  static const String ppvUfcPerth2026Thumb =
      '$_ppvDir/ppv-ufc-perth-2026_thumb.jpg';
  static const String ppvIbc03Thumb = '$_ppvDir/ppv-ibc-03_thumb.jpg';
  static const String ppvEternal80Thumb = '$_ppvDir/ppv-eternal-80_thumb.jpg';
  static const String ppvEliteFsCairnsThumb =
      '$_ppvDir/ppv-elite-fs-cairns_thumb.jpg';
  static const String ppvUltimateLegends2026Thumb =
      '$_ppvDir/ppv-ultimate-legends-apr-2026_thumb.jpg';
  static const String ppvUfc327Thumb = '$_ppvDir/ppv-ufc-327_thumb.jpg';
  static const String ppvUfc328Thumb = '$_ppvDir/ppv-ufc-328_thumb.jpg';
  static const String ppvPflPittsburgh2026Thumb =
      '$_ppvDir/ppv-pfl-pittsburgh-2026_thumb.jpg';
  static const String ppvBkfc72Thumb = '$_ppvDir/ppv-bkfc-72_thumb.jpg';
  static const String ppvOne170Thumb = '$_ppvDir/ppv-one-170_thumb.jpg';
  static const String ppvHex25Thumb = '$_ppvDir/ppv-hex-25_thumb.jpg';
  static const String ppvBkfcTownsvilleHepiThumb =
      '$_ppvDir/ppv-bkfc-townsville-hepi_thumb.jpg';
  static const String ppvBkfcNewcastleThumb =
      '$_ppvDir/ppv-bkfc-newcastle_thumb.jpg';
  static const String ppvIfmaAntalyacupThumb =
      '$_ppvDir/ppv-ifma-antalyacup_thumb.jpg';
  static const String ppvLegends45Thumb = '$_ppvDir/ppv-legends45_thumb.jpg';
  static const String ppvEternal88Thumb = '$_ppvDir/ppv-eternal88_thumb.jpg';
  static const String ppvAdelaideCs12Thumb =
      '$_ppvDir/ppv-adelaide-cs12_thumb.jpg';
  static const String ppvUfcParamountFightnightThumb =
      '$_ppvDir/ppv-ufc-paramount-fightnight_thumb.jpg';
  static const String ppvBrisbaneBonanzaThumb =
      '$_ppvDir/ppv-brisbane-bonanza_thumb.jpg';
  static const String ppvWestcoastWarriors33Thumb =
      '$_ppvDir/ppv-westcoast-warriors33_thumb.jpg';

  // ── PPV lookup maps ────────────────────────────────────────────────────
  static const _ppvHeroMap = <String, String>{
    'ppv-ufc-perth-2026': ppvUfcPerth2026Hero,
    'ppv-ibc-03': ppvIbc03Hero,
    'ppv-eternal-80': ppvEternal80Hero,
    'ppv-elite-fs-cairns': ppvEliteFsCairnsHero,
    'ppv-ultimate-legends-apr-2026': ppvUltimateLegends2026Hero,
    'ppv-ufc-327': ppvUfc327Hero,
    'ppv-ufc-328': ppvUfc328Hero,
    'ppv-pfl-pittsburgh-2026': ppvPflPittsburgh2026Hero,
    'ppv-bkfc-72': ppvBkfc72Hero,
    'ppv-one-170': ppvOne170Hero,
    'ppv-hex-25': ppvHex25Hero,
    'ppv-bkfc-townsville-hepi': ppvBkfcTownsvilleHepiHero,
    'ppv-bkfc-newcastle': ppvBkfcNewcastleHero,
    'ppv-ifma-antalyacup': ppvIfmaAntalyacupHero,
    'ppv-legends45': ppvLegends45Hero,
    'ppv-eternal88': ppvEternal88Hero,
    'ppv-adelaide-cs12': ppvAdelaideCs12Hero,
    'ppv-ufc-paramount-fightnight': ppvUfcParamountFightnightHero,
    'ppv-brisbane-bonanza': ppvBrisbaneBonanzaHero,
    'ppv-westcoast-warriors33': ppvWestcoastWarriors33Hero,
  };

  static const _ppvThumbMap = <String, String>{
    'ppv-ufc-perth-2026': ppvUfcPerth2026Thumb,
    'ppv-ibc-03': ppvIbc03Thumb,
    'ppv-eternal-80': ppvEternal80Thumb,
    'ppv-elite-fs-cairns': ppvEliteFsCairnsThumb,
    'ppv-ultimate-legends-apr-2026': ppvUltimateLegends2026Thumb,
    'ppv-ufc-327': ppvUfc327Thumb,
    'ppv-ufc-328': ppvUfc328Thumb,
    'ppv-pfl-pittsburgh-2026': ppvPflPittsburgh2026Thumb,
    'ppv-bkfc-72': ppvBkfc72Thumb,
    'ppv-one-170': ppvOne170Thumb,
    'ppv-hex-25': ppvHex25Thumb,
    'ppv-bkfc-townsville-hepi': ppvBkfcTownsvilleHepiThumb,
    'ppv-bkfc-newcastle': ppvBkfcNewcastleThumb,
    'ppv-ifma-antalyacup': ppvIfmaAntalyacupThumb,
    'ppv-legends45': ppvLegends45Thumb,
    'ppv-eternal88': ppvEternal88Thumb,
    'ppv-adelaide-cs12': ppvAdelaideCs12Thumb,
    'ppv-ufc-paramount-fightnight': ppvUfcParamountFightnightThumb,
    'ppv-brisbane-bonanza': ppvBrisbaneBonanzaThumb,
    'ppv-westcoast-warriors33': ppvWestcoastWarriors33Thumb,
  };

  static const _ppvBannerMap = <String, String>{
    'ppv-ufc-perth-2026': ppvUfcPerth2026Banner,
    'ppv-ibc-03': ppvIbc03Banner,
    'ppv-bkfc-72': ppvBkfc72Banner,
    'ppv-hex-25': ppvHex25Banner,
    'ppv-ultimate-legends-apr-2026': ppvUltimateLegends2026Banner,
    'ppv-bkfc-townsville-hepi': ppvBkfcTownsvilleHepiBanner,
    'ppv-legends45': ppvLegends45Banner,
    'ppv-eternal88': ppvEternal88Banner,
    'ppv-adelaide-cs12': ppvAdelaideCs12Banner,
    'ppv-ufc-paramount-fightnight': ppvUfcParamountFightnightBanner,
  };

  static const _ppvEventAliasMap = <String, String>{
    'ufc-fight-night-live': 'ppv-ufc-paramount-fightnight',
    'ufc-fn-march-15': 'ppv-ufc-paramount-fightnight',
    'ufc-fn-march-22': 'ppv-ufc-paramount-fightnight',
    'one-friday-fights-live': 'ppv-one-170',
    'one-fight-night-30': 'ppv-one-170',
    'ufc-314': 'ppv-ufc-328',
    'ufc-314-april': 'ppv-ufc-328',
    'ufc-315-may': 'ppv-ufc-327',
    'canelo-vs-benavidez': 'ppv-adelaide-cs12',
    'ibc-04-las-vegas': 'ppv-ibc-03',
  };

  static const _ppvDateMap = <String, String>{
    'ppv-ibc-03': '2026-03-07',
    'ppv-pfl-pittsburgh-2026': '2026-03-28',
    'ppv-brisbane-bonanza': '2026-04-04',
    'ppv-bkfc-72': '2026-04-05',
    'ppv-eternal-80': '2026-04-12',
    'ppv-bkfc-townsville-hepi': '2026-04-18',
    'ppv-ultimate-legends-apr-2026': '2026-04-24',
    'ppv-ufc-perth-2026': '2026-05-02',
    'ppv-adelaide-cs12': '2026-05-16',
    'ppv-ifma-antalyacup': '2026-05-22',
    'ppv-ufc-paramount-fightnight': '2026-05-30',
    'ppv-eternal88': '2026-06-06',
    'ppv-bkfc-newcastle': '2026-06-14',
  };

  static const _ppvUrlHintMap = <String, List<String>>{
    'ppv-ufc-perth-2026': [
      'ufc-perth-2026',
      'ufc-fight-night-perth',
      'burns-malott',
      'kayosports.com.au/ufc-perth-2026',
      'espnplus.com/ufc-328',
    ],
    'ppv-ibc-03': [
      'ppv-ibc-03',
      'ibc-03-gold-coast',
      'gold-coast-brawl',
      'international-brawling',
    ],
    'ppv-eternal-80': ['ppv-eternal-80', 'eternal-mma-perth-80'],
    'ppv-elite-fs-cairns': ['ppv-elite-fs-cairns', 'elite-fight-series-cairns'],
    'ppv-ultimate-legends-apr-2026': [
      'ppv-ultimate-legends-apr-2026',
      'ultimate-legends-apr-2026',
      'ultimate legends fight night',
      'fight week',
      'livecombatsports.com.au',
      'live combat sports',
      'melbourne pavilion',
      'roesler',
      'conor-wallace',
    ],
    'ppv-ufc-327': ['ppv-ufc-327', 'ufc-327', 'zuffa-boxing'],
    'ppv-ufc-328': ['ppv-ufc-328', 'ufc-328', 'ufc-323', 'chimaev', 'sydney'],
    'ppv-pfl-pittsburgh-2026': [
      'ppv-pfl-pittsburgh-2026',
      'pfl-pittsburgh-2026',
      'espn.com/pfl',
    ],
    'ppv-bkfc-72': ['ppv-bkfc-72', 'bkfc-72', 'knucklemania'],
    'ppv-one-170': ['ppv-one-170', 'one-170', 'watch.onefc.com', 'one-samurai'],
    'ppv-hex-25': ['ppv-hex-25', 'hex-25'],
    'ppv-bkfc-townsville-hepi': [
      'ppv-bkfc-townsville-hepi',
      'bkfc-fight-night-australia',
      'watch.bkfc.com/videos/697',
      'townsville',
      'hepi',
    ],
    'ppv-bkfc-newcastle': [
      'ppv-bkfc-newcastle',
      'bkfc-newcastle',
      'tszyu-diaz',
      'foxsports.com.au/tszyu-diaz',
      'newcastle',
    ],
    'ppv-ifma-antalyacup': [
      'ppv-ifma-antalyacup',
      'ifma-antalyacup',
      'antalya',
      'rajadamnern',
      'wkf',
    ],
    'ppv-legends45': [
      'ppv-legends45',
      'legends45',
      'cage-warriors',
      'cage-titans',
      'ckb',
    ],
    'ppv-eternal88': [
      'ppv-eternal88',
      'eternal88',
      'eternal-105',
      'eternal-106',
    ],
    'ppv-adelaide-cs12': ['ppv-adelaide-cs12', 'adelaide-cs12', 'adelaide'],
    'ppv-ufc-paramount-fightnight': [
      'ppv-ufc-paramount-fightnight',
      'ufc-paramount-fightnight',
      'ufc fight night',
      'paramount+',
      'paramountplus.com',
      'ufc apex',
    ],
    'ppv-brisbane-bonanza': [
      'ppv-brisbane-bonanza',
      'brisbane-bonanza',
      'brace',
    ],
    'ppv-westcoast-warriors33': [
      'ppv-westcoast-warriors33',
      'westcoast-warriors33',
      'king-of-the-ring',
    ],
  };

  static String _normalizePosterLookupKey(String value) {
    final normalized = value
        .trim()
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9]+'), '-')
        .replaceAll(RegExp(r'-+'), '-');
    return normalized.replaceAll(RegExp(r'^-|-$'), '');
  }

  static bool _isKnownPpvKey(String key) {
    return _ppvHeroMap.containsKey(key) ||
        _ppvThumbMap.containsKey(key) ||
        _ppvBannerMap.containsKey(key);
  }

  static String _posterVariantPath(String key, String variant) {
    return '$_ppvDir/${key}_${variant.toLowerCase()}.jpg';
  }

  static String? _posterAssetForVariant(String key, String variant) {
    if (!_isKnownPpvKey(key)) {
      return null;
    }

    switch (variant.toLowerCase()) {
      case 'thumb':
        return _ppvThumbMap[key] ?? _posterVariantPath(key, 'thumb');
      case 'banner':
        return _ppvBannerMap[key] ?? _posterVariantPath(key, 'banner');
      case 'preview':
        return _posterVariantPath(key, 'preview');
      case 'portrait':
        return _posterVariantPath(key, 'portrait');
      case 'hero':
      default:
        return _ppvHeroMap[key] ?? _posterVariantPath(key, 'hero');
    }
  }

  static String? _posterKeyFromAssetUrl(String? url) {
    if (url == null || url.trim().isEmpty) {
      return null;
    }

    final normalized = url.trim().toLowerCase();
    final match = RegExp(
      r'assets/ppv/(ppv-[a-z0-9-]+)_(hero|thumb|banner|preview|portrait)\.(jpg|webp)$',
    ).firstMatch(normalized);
    return match?.group(1);
  }

  static String? _posterAssetForKey(String key, {bool preferThumb = false}) {
    return _posterAssetForVariant(key, preferThumb ? 'thumb' : 'hero');
  }

  static String? _posterAssetForEventId(
    String? eventId, {
    bool preferThumb = false,
  }) {
    if (eventId == null || eventId.trim().isEmpty) {
      return null;
    }

    final normalized = _normalizePosterLookupKey(eventId);
    final candidates = <String>{eventId.trim(), normalized};
    final aliased = _ppvEventAliasMap[normalized];
    if (aliased != null) {
      candidates.add(aliased);
    }
    for (final value in List<String>.from(candidates)) {
      if (value.startsWith('demo-')) {
        candidates.add(value.substring(5));
      }
      if (value.startsWith('ppv-')) {
        candidates.add(value.substring(4));
      } else {
        candidates.add('ppv-$value');
      }
    }

    for (final candidate in candidates) {
      final resolved = _posterAssetForKey(candidate, preferThumb: preferThumb);
      if (resolved != null) {
        return resolved;
      }
    }
    return null;
  }

  static String? _posterAssetForEventIdVariant(
    String? eventId, {
    required String variant,
  }) {
    if (eventId == null || eventId.trim().isEmpty) {
      return null;
    }

    final normalized = _normalizePosterLookupKey(eventId);
    final candidates = <String>{eventId.trim(), normalized};
    final aliased = _ppvEventAliasMap[normalized];
    if (aliased != null) {
      candidates.add(aliased);
    }
    for (final value in List<String>.from(candidates)) {
      if (value.startsWith('demo-')) {
        candidates.add(value.substring(5));
      }
      if (value.startsWith('ppv-')) {
        candidates.add(value.substring(4));
      } else {
        candidates.add('ppv-$value');
      }
    }

    for (final candidate in candidates) {
      final resolved = _posterAssetForVariant(candidate, variant);
      if (resolved != null) {
        return resolved;
      }
    }
    return null;
  }

  static String? _posterKeyFromUrls({
    String? eventId,
    String? streamUrl,
    String? ticketUrl,
  }) {
    final haystack = [eventId, streamUrl, ticketUrl]
        .whereType<String>()
        .map((value) => Uri.decodeFull(value).toLowerCase())
        .join(' ');
    if (haystack.isEmpty) {
      return null;
    }

    for (final entry in _ppvUrlHintMap.entries) {
      if (entry.value.any(haystack.contains)) {
        return entry.key;
      }
    }
    return null;
  }

  static bool _matchesExpectedEventDate(String key, DateTime? eventDate) {
    final expected = _ppvDateMap[key];
    if (expected == null || eventDate == null) {
      return false;
    }

    final parsed = DateTime.tryParse(expected);
    if (parsed == null) {
      return false;
    }

    return eventDate.year == parsed.year &&
        eventDate.month == parsed.month &&
        eventDate.day == parsed.day;
  }

  static bool _matchesNearbyEventDate(
    String key,
    DateTime? eventDate, {
    int toleranceDays = 45,
  }) {
    final expected = _ppvDateMap[key];
    if (expected == null || eventDate == null) {
      return false;
    }

    final parsed = DateTime.tryParse(expected);
    if (parsed == null) {
      return false;
    }

    return eventDate.difference(parsed).inDays.abs() <= toleranceDays;
  }

  static bool _hasStrongPosterSignal(
    String key,
    String? title,
    String? promoter,
  ) {
    final normalizedTitle = (title ?? '').toLowerCase();
    final normalizedPromoter = (promoter ?? '').toLowerCase();

    switch (key) {
      case 'ppv-ultimate-legends-apr-2026':
        return normalizedTitle.contains('ultimate legends') ||
            normalizedPromoter.contains('live combat sports');
      case 'ppv-ufc-paramount-fightnight':
        return normalizedTitle.contains('ufc fight night') ||
            normalizedTitle.contains('strickland') ||
            normalizedTitle.contains('du plessis') ||
            normalizedTitle.contains('allen') ||
            normalizedTitle.contains('imavov') ||
            normalizedTitle.contains('moreno') ||
            normalizedTitle.contains('royval') ||
            normalizedPromoter.contains('paramount');
      case 'ppv-ufc-328':
        return normalizedTitle.contains('ufc 314') ||
            normalizedTitle.contains('makhachev') ||
            normalizedTitle.contains('oliveira') ||
            normalizedTitle.contains('ufc 315') ||
            normalizedTitle.contains('pereira') ||
            normalizedTitle.contains('ankalaev');
      case 'ppv-ufc-327':
        return normalizedTitle.contains('ufc 315') ||
            normalizedTitle.contains('pereira') ||
            normalizedTitle.contains('ankalaev');
      case 'ppv-ibc-03':
        return normalizedTitle.contains('ibc') ||
            normalizedTitle.contains('international brawling') ||
            normalizedTitle.contains('cutler') ||
            normalizedTitle.contains('modini') ||
            normalizedTitle.contains('hardman') ||
            normalizedTitle.contains('tuhu') ||
            normalizedPromoter.contains('international brawling');
      case 'ppv-bkfc-townsville-hepi':
        return normalizedTitle.contains('townsville') ||
            normalizedTitle.contains('haze hepi') ||
            normalizedTitle.contains('wisniewski') ||
            normalizedTitle.contains('fight night australia') ||
            normalizedPromoter.contains('bare knuckle');
      case 'ppv-bkfc-72':
        return normalizedTitle.contains('bkfc 72') ||
            normalizedTitle.contains('knucklemania') ||
            normalizedTitle.contains('christine ferea') ||
            normalizedTitle.contains('misfit mafia') ||
            normalizedTitle.contains('bare knuckle queens');
      case 'ppv-eternal-80':
        return normalizedTitle.contains('eternal 80');
      case 'ppv-eternal88':
        return normalizedTitle.contains('eternal mma') ||
            normalizedPromoter.contains('eternal mma');
      case 'ppv-hex-25':
        return normalizedTitle.contains('hex fight series') ||
            normalizedTitle.contains('hex fs') ||
            normalizedPromoter.contains('hex fight series');
      case 'ppv-ufc-perth-2026':
        return normalizedTitle.contains('ufc perth') ||
            normalizedTitle.contains('della maddalena') ||
            normalizedTitle.contains('prates');
      case 'ppv-adelaide-cs12':
        return normalizedTitle.contains('opetaia') ||
            normalizedTitle.contains('canelo') ||
            normalizedTitle.contains('benavidez') ||
            normalizedTitle.contains('justis huni') ||
            normalizedTitle.contains('pierce o\'leary');
      case 'ppv-one-170':
        return normalizedTitle.contains('one friday fights') ||
            normalizedTitle.contains('one fight night') ||
            normalizedTitle.contains('superbon') ||
            normalizedTitle.contains('grigorian') ||
            normalizedTitle.contains('lumpinee') ||
            normalizedPromoter.contains('one championship');
      default:
        return false;
    }
  }

  static String? _mappedEventPosterKey(String? title, String? promoter) {
    final normalizedTitle = (title ?? '').toLowerCase();
    final normalizedPromoter = (promoter ?? '').toLowerCase();

    if (normalizedTitle.contains('international brawling championship') ||
        normalizedTitle.contains('ibc iii') ||
        normalizedTitle.contains('cutler') ||
        normalizedTitle.contains('modini') ||
        normalizedTitle.contains('hardman') ||
        normalizedTitle.contains('tuhu') ||
        normalizedPromoter.contains('international brawling')) {
      return 'ppv-ibc-03';
    }
    if (normalizedTitle.contains('bkfc fight night australia') ||
        normalizedTitle.contains('townsville') ||
        normalizedTitle.contains('haze hepi') ||
        normalizedTitle.contains('wisniewski')) {
      return 'ppv-bkfc-townsville-hepi';
    }
    if (normalizedTitle.contains('bkfc 72') ||
        normalizedTitle.contains('knucklemania')) {
      return 'ppv-bkfc-72';
    }
    if (normalizedTitle.contains('christine ferea') ||
        normalizedTitle.contains('misfit mafia') ||
        normalizedTitle.contains('bare knuckle queens')) {
      return 'ppv-bkfc-72';
    }
    if (normalizedTitle.contains('ufc') && normalizedTitle.contains('perth')) {
      return 'ppv-ufc-perth-2026';
    }
    if (normalizedTitle.contains('della maddalena') ||
        normalizedTitle.contains('prates')) {
      return 'ppv-ufc-perth-2026';
    }
    if (normalizedTitle.contains('ufc 328') ||
        normalizedTitle.contains('chimaev') ||
        normalizedTitle.contains('ufc 323') ||
        (normalizedTitle.contains('ufc') &&
            normalizedTitle.contains('sydney'))) {
      return 'ppv-ufc-328';
    }
    if (normalizedTitle.contains('ufc 314') ||
        normalizedTitle.contains('makhachev') ||
        normalizedTitle.contains('oliveira')) {
      return 'ppv-ufc-328';
    }
    if (normalizedTitle.contains('ufc 315') ||
        normalizedTitle.contains('pereira') ||
        normalizedTitle.contains('ankalaev')) {
      return 'ppv-ufc-327';
    }
    if (normalizedTitle.contains('tszyu') ||
        normalizedTitle.contains('butcher and the bull')) {
      return 'ppv-bkfc-newcastle';
    }
    if (normalizedTitle.contains('zuffa boxing') ||
        normalizedPromoter.contains('zuffa')) {
      return 'ppv-ufc-327';
    }
    if (normalizedTitle.contains('ufc fight night') ||
        normalizedTitle.contains('ufc fn')) {
      return 'ppv-ufc-paramount-fightnight';
    }
    if (normalizedPromoter.contains('pfl') ||
        normalizedPromoter.contains('professional fighters')) {
      return 'ppv-pfl-pittsburgh-2026';
    }
    if (normalizedPromoter.contains('one championship') ||
        normalizedTitle.startsWith('one ')) {
      return 'ppv-one-170';
    }
    if (normalizedTitle.contains('hex fight series') ||
        normalizedTitle.contains('hex fs') ||
        normalizedPromoter.contains('hex fight series') ||
        normalizedTitle.contains('hex') ||
        normalizedPromoter.contains('hex')) {
      return 'ppv-hex-25';
    }
    if (normalizedTitle.contains('eternal 80')) {
      return 'ppv-eternal-80';
    }
    if (normalizedTitle.contains('eternal mma') ||
        normalizedPromoter.contains('eternal mma')) {
      return 'ppv-eternal88';
    }
    if (normalizedTitle.contains('eternal') ||
        normalizedPromoter.contains('eternal')) {
      return 'ppv-eternal88';
    }
    if (normalizedTitle.contains('ultimate legends')) {
      return 'ppv-ultimate-legends-apr-2026';
    }
    if (normalizedTitle.contains('bkfc') ||
        normalizedPromoter.contains('bare knuckle')) {
      return 'ppv-bkfc-newcastle';
    }
    if (normalizedTitle.contains('glory') ||
        normalizedPromoter.contains('glory')) {
      return 'ppv-westcoast-warriors33';
    }
    if (normalizedTitle.contains('k-1') || normalizedPromoter.contains('k-1')) {
      return 'ppv-ifma-antalyacup';
    }
    if (normalizedTitle.contains('adelaide') ||
        normalizedTitle.contains('boxing australia')) {
      return 'ppv-adelaide-cs12';
    }
    if (normalizedTitle.contains('opetaia') ||
        normalizedTitle.contains('canelo') ||
        normalizedTitle.contains('benavidez') ||
        normalizedTitle.contains('justis huni') ||
        normalizedTitle.contains('pierce o\'leary')) {
      return 'ppv-adelaide-cs12';
    }
    if (normalizedTitle.contains('brisbane') ||
        normalizedTitle.contains('brace')) {
      return 'ppv-brisbane-bonanza';
    }
    if (normalizedTitle.contains('yokkao') ||
        normalizedTitle.contains('muay thai grand prix') ||
        normalizedTitle.contains('wkf') ||
        normalizedPromoter.contains('wkf') ||
        normalizedTitle.contains('rajadamnern')) {
      return 'ppv-ifma-antalyacup';
    }
    if (normalizedTitle.contains('cage titans') ||
        normalizedTitle.contains('cage warriors') ||
        normalizedTitle.contains('ckb') ||
        normalizedPromoter.contains('summit')) {
      return 'ppv-legends45';
    }
    if (normalizedPromoter.contains('duco') ||
        normalizedTitle.contains('parker') ||
        normalizedTitle.contains('joshua') ||
        normalizedPromoter.contains('matchroom')) {
      return 'ppv-adelaide-cs12';
    }
    if (normalizedTitle.contains('king of the ring')) {
      return 'ppv-westcoast-warriors33';
    }
    if (normalizedTitle.contains('no scorecards')) {
      return 'ppv-brisbane-bonanza';
    }
    if (normalizedTitle.contains('elite') &&
        normalizedTitle.contains('cairns')) {
      return 'ppv-elite-fs-cairns';
    }
    if (normalizedTitle.contains('ibc') ||
        normalizedPromoter == 'ibc' ||
        normalizedTitle.contains('international brawling')) {
      return 'ppv-ibc-03';
    }

    return null;
  }

  static String? posterAssetForEventMetadata({
    String? eventId,
    String? title,
    String? promoter,
    DateTime? eventDate,
    String? streamUrl,
    String? ticketUrl,
    bool preferThumb = false,
  }) {
    final exact = _posterAssetForEventId(eventId, preferThumb: preferThumb);
    if (exact != null) {
      return exact;
    }

    final fromUrls = _posterKeyFromUrls(
      eventId: eventId,
      streamUrl: streamUrl,
      ticketUrl: ticketUrl,
    );
    if (fromUrls != null) {
      return _posterAssetForKey(fromUrls, preferThumb: preferThumb);
    }

    final mappedKey = _mappedEventPosterKey(title, promoter);
    if (mappedKey != null &&
        (_matchesExpectedEventDate(mappedKey, eventDate) ||
            _matchesNearbyEventDate(mappedKey, eventDate) ||
            _hasStrongPosterSignal(mappedKey, title, promoter))) {
      return _posterAssetForKey(mappedKey, preferThumb: preferThumb);
    }

    return null;
  }

  static String? posterAssetForEventMetadataVariant({
    String? eventId,
    String? title,
    String? promoter,
    DateTime? eventDate,
    String? streamUrl,
    String? ticketUrl,
    String variant = 'hero',
  }) {
    final exact = _posterAssetForEventIdVariant(eventId, variant: variant);
    if (exact != null) {
      return exact;
    }

    final fromUrls = _posterKeyFromUrls(
      eventId: eventId,
      streamUrl: streamUrl,
      ticketUrl: ticketUrl,
    );
    if (fromUrls != null) {
      return _posterAssetForVariant(fromUrls, variant);
    }

    final mappedKey = _mappedEventPosterKey(title, promoter);
    if (mappedKey != null &&
        (_matchesExpectedEventDate(mappedKey, eventDate) ||
            _matchesNearbyEventDate(mappedKey, eventDate) ||
            _hasStrongPosterSignal(mappedKey, title, promoter))) {
      return _posterAssetForVariant(mappedKey, variant);
    }

    return null;
  }

  /// Returns the generated hero poster path for a known PPV event ID,
  /// or falls back to the sport-specific placeholder.
  static String ppvPosterForEvent(String eventId, {String? sport}) {
    final path = _ppvHeroMap[eventId];
    if (path != null) return path;
    return posterForSport(sport);
  }

  /// Returns the generated thumbnail path for a known PPV event ID.
  static String ppvThumbForEvent(String eventId, {String? sport}) {
    final path = _ppvThumbMap[eventId];
    if (path != null) return path;
    return posterForSport(sport);
  }

  /// Returns the generated banner path for a known PPV event ID.
  static String ppvBannerForEvent(String eventId, {String? sport}) {
    final path = _ppvBannerMap[eventId];
    if (path != null) return path;
    return ppvPosterForEvent(eventId, sport: sport);
  }

  static String posterForEventMetadata({
    String? eventId,
    String? title,
    String? promoter,
    String? sport,
    DateTime? eventDate,
    String? streamUrl,
    String? ticketUrl,
    bool preferThumb = false,
  }) {
    return posterAssetForEventMetadataVariant(
          eventId: eventId,
          title: title,
          promoter: promoter,
          eventDate: eventDate,
          streamUrl: streamUrl,
          ticketUrl: ticketUrl,
          variant: preferThumb ? 'thumb' : 'hero',
        ) ??
        posterForSport(sport);
  }

  static String posterVariantFromUrl(String? url, {required String variant}) {
    final normalized = url?.trim();
    if (normalized == null || normalized.isEmpty) {
      return '';
    }

    final key = _posterKeyFromAssetUrl(normalized);
    if (key == null) {
      return normalized;
    }

    return _posterAssetForVariant(key, variant) ?? normalized;
  }

  static bool isSpecificEventPosterAsset(String? url) {
    if (url == null || url.trim().isEmpty) {
      return false;
    }

    final normalized = url.trim();
    return RegExp(
      r'^assets/ppv/ppv-[a-z0-9-]+_(hero|thumb|banner|preview|portrait)\.(jpg|webp)$',
    ).hasMatch(normalized);
  }

  static bool isGenericPosterAsset(String? url) {
    if (url == null) return true;
    final normalized = url.trim();
    if (normalized.isEmpty) return true;
    return normalized == bgHero ||
        normalized == bgAction ||
        normalized == bgEvent ||
        normalized == bgPromo ||
        normalized == bgLogo1024 ||
        normalized == bgLogoSmall ||
        normalized == bgCentral ||
        normalized == bgResized ||
        normalized == bgSquare;
  }

  /// Returns a branded poster image for the given sport type.
  static String posterForSport(String? sportType) {
    switch (sportType?.toLowerCase()) {
      case 'mma':
        return bgAction;
      case 'boxing':
        return bgEvent;
      case 'kickboxing':
        return bgPromo;
      case 'muay thai':
        return bgCentral;
      case 'bkfc':
      case 'bare knuckle':
        return bgHero;
      case 'brawling':
        return bgSquare;
      case 'pro wrestling':
        return bgCentral;
      case 'drone racing':
        return bgResized;
      default:
        return bgLogoSmall;
    }
  }

  /// Returns `true` when the URL is a local asset path (not http).
  static bool isLocalAsset(String url) =>
      url.startsWith('assets/') || url.startsWith('asset:');

  /// Smart image widget — handles both local assets and network URLs safely.
  /// Sanitizes URLs through ImageUrlSanitizer before resolving.
  static ImageProvider resolveImage(String url) {
    final safe = ImageUrlSanitizer.sanitize(
      url,
    );
    if (isLocalAsset(safe)) {
      return AssetImage(safe);
    }
    return NetworkImage(safe);
  }

  /// Sanitize + resolve: the ONE call every screen should use for ImageProvider.
  /// Handles null, empty, blocked, asset paths, and network URLs.
  static ImageProvider safeProvider(String? url, {String? fallback}) {
    final safe = ImageUrlSanitizer.sanitize(
      url,
      fallback: fallback ?? dfcBrandedPlaceholder,
    );
    return resolveImage(safe);
  }

  // ── Broadcast channel brand colors ─────────────────────────────────────
  /// Returns a brand-accurate (bg, text) color pair for the given broadcast.
  /// Used by the broadcast badge widget on event cards.
  static ({Color bg, Color fg}) broadcastColors(String channel) {
    switch (_normalizeBroadcast(channel)) {
      case 'paramount+':
        return (bg: const Color(0xFF0064FF), fg: const Color(0xFFFFFFFF));
      case 'kayo sports':
        return (bg: const Color(0xFF00C853), fg: const Color(0xFF000000));
      case 'bkfc app':
        return (bg: const Color(0xFFE53935), fg: const Color(0xFFFFFFFF));
      case 'ufc fight pass':
        return (bg: const Color(0xFFD4AF37), fg: const Color(0xFF000000));
      case 'foxtel':
        return (bg: const Color(0xFFFF6600), fg: const Color(0xFFFFFFFF));
      case 'dazn':
        return (bg: const Color(0xFFFFBC00), fg: const Color(0xFF000000));
      case 'espn+':
        return (bg: const Color(0xFFCC0000), fg: const Color(0xFFFFFFFF));
      case 'prime video':
        return (bg: const Color(0xFF00A8E1), fg: const Color(0xFF000000));
      case 'stan sport':
        return (bg: const Color(0xFF0072CE), fg: const Color(0xFFFFFFFF));
      case 'sky sports':
        return (bg: const Color(0xFFE10600), fg: const Color(0xFFFFFFFF));
      case 'bt sport':
        return (bg: const Color(0xFF1A1A2E), fg: const Color(0xFFFFFFFF));
      case 'showtime':
        return (bg: const Color(0xFFFF0000), fg: const Color(0xFFFFFFFF));
      case 'fite':
        return (bg: const Color(0xFF7B2BFC), fg: const Color(0xFFFFFFFF));
      case 'dfc fightpipe':
      case 'dfc live':
        return (bg: const Color(0xFF00E5FF), fg: const Color(0xFF000000));
      default:
        return (bg: const Color(0xFF1A1A2E), fg: const Color(0xFFFFFFFF));
    }
  }

  /// Normalize broadcast string for matching (lowercase, trim whitespace).
  static String _normalizeBroadcast(String channel) {
    return channel.trim().toLowerCase();
  }

  /// All supported PPV/broadcast channels.
  static const List<String> supportedBroadcasts = [
    'Paramount+',
    'Kayo Sports',
    'BKFC App',
    'UFC Fight Pass',
    'Foxtel',
    'DAZN',
    'ESPN+',
    'Prime Video',
    'Stan Sport',
    'Sky Sports',
    'BT Sport',
    'Showtime',
    'FITE',
    'DFC FightPipe',
    'DFC Live',
  ];
}
